export interface GlossaryTerm {
  term: string;
  definition: string;
  category: string;
}

export const GLOSSARY_CATEGORIES = [
  "Market Basics",
  "Financial Statements",
  "Valuation",
  "Technical Analysis",
  "Trading",
  "Options & Derivatives",
  "Fixed Income",
  "Economics",
  "Portfolio Management",
  "Risk & Regulation",
];

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // Market Basics
  { term: "Stock", definition: "A share of ownership in a publicly traded company. When you buy stock, you become a partial owner (shareholder) entitled to a proportional claim on earnings and assets.", category: "Market Basics" },
  { term: "Share", definition: "A single unit of stock representing fractional ownership of a company. Companies issue shares to raise capital from investors.", category: "Market Basics" },
  { term: "Ticker Symbol", definition: "A unique 1–5 letter code assigned to a publicly traded company (e.g., AAPL for Apple, MSFT for Microsoft) used to identify it on exchanges.", category: "Market Basics" },
  { term: "Stock Exchange", definition: "A regulated marketplace where securities are bought and sold. Major exchanges include NYSE, NASDAQ, LSE, and NSE.", category: "Market Basics" },
  { term: "Market Capitalization", definition: "The total market value of a company's outstanding shares. Calculated as share price × total shares outstanding. Used to classify companies as large-cap, mid-cap, or small-cap.", category: "Market Basics" },
  { term: "IPO (Initial Public Offering)", definition: "The first time a private company sells shares to the public. The company transitions from private to publicly traded, raising capital from outside investors.", category: "Market Basics" },
  { term: "Bull Market", definition: "A sustained period where stock prices rise 20% or more from recent lows, typically accompanied by strong economic growth and investor optimism.", category: "Market Basics" },
  { term: "Bear Market", definition: "A sustained decline of 20% or more from recent highs, often accompanied by pessimism, economic slowdown, and widespread selling.", category: "Market Basics" },
  { term: "Index", definition: "A statistical measure tracking the performance of a group of stocks (e.g., S&P 500 tracks 500 large U.S. companies). Used as benchmarks for market performance.", category: "Market Basics" },
  { term: "Dividend", definition: "A portion of a company's profits distributed to shareholders, usually quarterly. Expressed as a per-share amount or yield (annual dividend ÷ stock price).", category: "Market Basics" },
  { term: "Blue Chip", definition: "Shares of a large, well-established, financially stable company with a long track record of reliable performance and often consistent dividend payments.", category: "Market Basics" },
  { term: "Penny Stock", definition: "Stocks trading below $5 per share, often from small companies with limited track records. Considered highly speculative due to low liquidity and limited financial disclosures.", category: "Market Basics" },
  { term: "ETF (Exchange-Traded Fund)", definition: "A fund that holds a basket of assets (stocks, bonds, etc.) and trades on an exchange like a single stock. Combines mutual fund diversification with stock-like trading flexibility.", category: "Market Basics" },
  { term: "Mutual Fund", definition: "A pooled investment vehicle professionally managed that invests in a diversified portfolio. Unlike ETFs, mutual funds are priced once daily after market close.", category: "Market Basics" },
  { term: "Bid Price", definition: "The highest price a buyer is willing to pay for a security at a given moment. The bid represents demand.", category: "Market Basics" },
  { term: "Ask Price", definition: "The lowest price a seller is willing to accept for a security. The difference between bid and ask is the 'spread,' reflecting liquidity.", category: "Market Basics" },
  { term: "Spread", definition: "The difference between the bid and ask price. Narrow spreads indicate high liquidity; wide spreads suggest lower trading activity.", category: "Market Basics" },
  { term: "Volume", definition: "The total number of shares traded during a specific time period. High volume indicates strong interest and liquidity; low volume may signal uncertainty.", category: "Market Basics" },
  { term: "Liquidity", definition: "How easily an asset can be bought or sold without significantly affecting its price. Cash is the most liquid asset; real estate is illiquid.", category: "Market Basics" },
  { term: "Volatility", definition: "The degree of price fluctuation over time. High volatility means large price swings (higher risk/reward); low volatility means more stable prices.", category: "Market Basics" },

  // Financial Statements
  { term: "Balance Sheet", definition: "A financial statement showing a company's assets, liabilities, and shareholders' equity at a specific point in time. Assets = Liabilities + Equity.", category: "Financial Statements" },
  { term: "Income Statement", definition: "A financial statement showing revenues, expenses, and profit over a period (quarter or year). Also called the profit and loss (P&L) statement.", category: "Financial Statements" },
  { term: "Cash Flow Statement", definition: "A financial statement tracking the actual movement of cash in and out of a business through operating, investing, and financing activities.", category: "Financial Statements" },
  { term: "Revenue", definition: "The total income a company earns from selling goods or services before any expenses are deducted. Also called the 'top line.'", category: "Financial Statements" },
  { term: "Net Income", definition: "The company's total profit after all expenses, interest, taxes, and deductions. Also called the 'bottom line' — what the company actually earned.", category: "Financial Statements" },
  { term: "Gross Profit", definition: "Revenue minus Cost of Goods Sold (COGS). It shows how much money remains after direct production costs but before operating expenses.", category: "Financial Statements" },
  { term: "Operating Income", definition: "Profit from core business operations after deducting operating expenses but before interest and taxes. Also called EBIT (Earnings Before Interest and Taxes).", category: "Financial Statements" },
  { term: "EBITDA", definition: "Earnings Before Interest, Taxes, Depreciation, and Amortization. A measure of core operating performance that strips out non-cash charges and financing costs.", category: "Financial Statements" },
  { term: "EPS (Earnings Per Share)", definition: "Net income divided by the number of outstanding shares. A key profitability metric showing how much profit each share generates.", category: "Financial Statements" },
  { term: "Free Cash Flow", definition: "Operating cash flow minus capital expenditures. Represents the cash available for dividends, debt repayment, buybacks, or reinvestment after maintaining assets.", category: "Financial Statements" },
  { term: "Depreciation", definition: "The systematic allocation of a tangible asset's cost over its useful life. A non-cash expense that reduces reported earnings but doesn't require cash outflow.", category: "Financial Statements" },
  { term: "Amortization", definition: "Similar to depreciation but for intangible assets (patents, software, goodwill). Spreads the cost of the asset over its useful life.", category: "Financial Statements" },
  { term: "Working Capital", definition: "Current assets minus current liabilities. Measures a company's ability to cover short-term obligations. Positive working capital indicates short-term financial health.", category: "Financial Statements" },
  { term: "Goodwill", definition: "An intangible asset recorded when a company acquires another for more than the fair value of its net assets. Represents brand value, customer relationships, and reputation.", category: "Financial Statements" },
  { term: "Retained Earnings", definition: "Cumulative net income that a company has kept rather than distributed as dividends. Reflects profits reinvested back into the business over time.", category: "Financial Statements" },
  { term: "Accounts Receivable", definition: "Money owed to a company by customers for goods or services delivered but not yet paid for. A current asset on the balance sheet.", category: "Financial Statements" },
  { term: "Accounts Payable", definition: "Money a company owes to suppliers or vendors for goods or services received but not yet paid for. A current liability on the balance sheet.", category: "Financial Statements" },
  { term: "Current Ratio", definition: "Current assets divided by current liabilities. A liquidity metric — above 1.0 means the company can cover short-term obligations.", category: "Financial Statements" },
  { term: "Debt-to-Equity Ratio", definition: "Total debt divided by shareholders' equity. Measures financial leverage — higher values mean the company relies more on debt financing.", category: "Financial Statements" },

  // Valuation
  { term: "P/E Ratio (Price-to-Earnings)", definition: "Stock price divided by earnings per share. Shows how much investors pay per dollar of earnings. A P/E of 20 means paying $20 for every $1 of annual earnings.", category: "Valuation" },
  { term: "Forward P/E", definition: "Stock price divided by estimated future earnings per share (next 12 months). Uses analyst projections rather than trailing earnings.", category: "Valuation" },
  { term: "P/B Ratio (Price-to-Book)", definition: "Stock price divided by book value per share. Compares market valuation to accounting value. A P/B below 1 may indicate undervaluation.", category: "Valuation" },
  { term: "P/S Ratio (Price-to-Sales)", definition: "Market cap divided by total revenue. Useful for valuing companies with no earnings yet. Lower P/S may indicate better value.", category: "Valuation" },
  { term: "PEG Ratio", definition: "P/E ratio divided by the earnings growth rate. A PEG of 1 suggests fair value; below 1 may indicate undervaluation relative to growth.", category: "Valuation" },
  { term: "EV/EBITDA", definition: "Enterprise Value divided by EBITDA. Compares total company value (including debt) to operating earnings. Useful for cross-company comparison.", category: "Valuation" },
  { term: "Enterprise Value (EV)", definition: "Market cap + total debt − cash and equivalents. Represents the total takeover cost of a company, accounting for both equity and debt holders.", category: "Valuation" },
  { term: "Intrinsic Value", definition: "The estimated true worth of a stock based on fundamental analysis (cash flows, growth, risk), independent of its current market price.", category: "Valuation" },
  { term: "DCF (Discounted Cash Flow)", definition: "A valuation method that estimates a company's worth by projecting future free cash flows and discounting them to present value using WACC.", category: "Valuation" },
  { term: "Book Value", definition: "Total assets minus total liabilities. Represents the net asset value of a company according to its balance sheet.", category: "Valuation" },
  { term: "Market Value", definition: "The current price the market assigns to a company's stock, reflecting investor sentiment, expectations, and market conditions.", category: "Valuation" },
  { term: "ROE (Return on Equity)", definition: "Net income divided by shareholders' equity. Measures how efficiently a company generates profit from its equity base. Higher is generally better.", category: "Valuation" },
  { term: "ROA (Return on Assets)", definition: "Net income divided by total assets. Measures how efficiently a company uses its assets to generate profit.", category: "Valuation" },
  { term: "WACC", definition: "Weighted Average Cost of Capital — the blended cost of debt and equity financing. Used as the discount rate in DCF valuations.", category: "Valuation" },
  { term: "Dividend Yield", definition: "Annual dividend per share divided by the stock price. Shows the cash return on investment from dividends alone, expressed as a percentage.", category: "Valuation" },
  { term: "Margin of Safety", definition: "The difference between a stock's intrinsic value and its purchase price. A core principle of value investing — buying at a discount provides a buffer.", category: "Valuation" },

  // Technical Analysis
  { term: "Moving Average (MA)", definition: "The average price over a specified number of periods (e.g., 50-day, 200-day). Smooths price data to identify trend direction.", category: "Technical Analysis" },
  { term: "SMA (Simple Moving Average)", definition: "An average calculated by summing closing prices over a period and dividing by the number of periods. Each data point has equal weight.", category: "Technical Analysis" },
  { term: "EMA (Exponential Moving Average)", definition: "A moving average that gives more weight to recent prices, making it more responsive to new information than the SMA.", category: "Technical Analysis" },
  { term: "RSI (Relative Strength Index)", definition: "A momentum oscillator (0–100) measuring the speed and change of price movements. Above 70 = overbought, below 30 = oversold.", category: "Technical Analysis" },
  { term: "MACD", definition: "Moving Average Convergence Divergence — a trend-following momentum indicator using the relationship between the 12-day and 26-day EMA.", category: "Technical Analysis" },
  { term: "Bollinger Bands", definition: "A volatility indicator with three lines: a 20-day SMA and two bands at ±2 standard deviations. Bands widen with volatility, narrow during calm periods.", category: "Technical Analysis" },
  { term: "Support Level", definition: "A price level where buying interest is strong enough to prevent further decline. The 'floor' where demand tends to emerge.", category: "Technical Analysis" },
  { term: "Resistance Level", definition: "A price level where selling pressure prevents further price increases. The 'ceiling' where supply tends to emerge.", category: "Technical Analysis" },
  { term: "Golden Cross", definition: "A bullish signal occurring when the 50-day MA crosses above the 200-day MA, suggesting potential upward momentum.", category: "Technical Analysis" },
  { term: "Death Cross", definition: "A bearish signal occurring when the 50-day MA crosses below the 200-day MA, suggesting potential downward momentum.", category: "Technical Analysis" },
  { term: "Candlestick Chart", definition: "A chart type showing open, high, low, and close prices for each period. The body shows open/close range; wicks show high/low extremes.", category: "Technical Analysis" },
  { term: "Head and Shoulders", definition: "A bearish reversal pattern with three peaks — a higher central peak (head) flanked by two lower peaks (shoulders). Breaking the neckline confirms reversal.", category: "Technical Analysis" },
  { term: "Double Bottom", definition: "A bullish reversal pattern where the price bounces twice from the same support level, forming a 'W' shape.", category: "Technical Analysis" },
  { term: "Breakout", definition: "When a stock's price moves above a resistance level or below a support level with significant volume, signaling a potential new trend.", category: "Technical Analysis" },

  // Trading
  { term: "Market Order", definition: "An order to buy or sell immediately at the best available current price. Prioritizes execution speed over price certainty.", category: "Trading" },
  { term: "Limit Order", definition: "An order to buy or sell at a specific price or better. Buy limits execute at or below your price; sell limits at or above.", category: "Trading" },
  { term: "Stop-Loss Order", definition: "An order to sell a security when it reaches a specified price, automatically limiting potential losses on a position.", category: "Trading" },
  { term: "Stop-Limit Order", definition: "Combines stop-loss and limit orders — triggered at the stop price but only executes at the limit price or better.", category: "Trading" },
  { term: "Short Selling", definition: "Borrowing shares to sell them at the current price, then buying them back later (hopefully at a lower price) to return. Profits from price declines.", category: "Trading" },
  { term: "Margin", definition: "Borrowed money from a broker used to buy securities. Margin amplifies both gains and losses. Requires a margin account and maintenance requirements.", category: "Trading" },
  { term: "Day Trading", definition: "Buying and selling securities within the same trading day, closing all positions before market close. Requires pattern day trader status above $25,000.", category: "Trading" },
  { term: "Swing Trading", definition: "Holding positions for days to weeks, aiming to profit from expected price swings. A middle ground between day trading and long-term investing.", category: "Trading" },
  { term: "Going Long", definition: "Buying a security with the expectation that its price will rise. The most common investment approach — buy low, sell high.", category: "Trading" },
  { term: "Going Short", definition: "Selling a borrowed security with the expectation that its price will fall, allowing you to buy it back cheaper. Profits from price declines.", category: "Trading" },
  { term: "Paper Trading", definition: "Simulated trading using virtual money to practice strategies without financial risk. Essential for beginners to build confidence and test approaches.", category: "Trading" },
  { term: "Commission", definition: "A fee charged by a broker for executing a trade. Many major brokers now offer commission-free trading for stocks and ETFs.", category: "Trading" },
  { term: "Slippage", definition: "The difference between the expected price of a trade and the actual execution price. Occurs in fast-moving or illiquid markets.", category: "Trading" },
  { term: "Fill", definition: "When a trade order is executed (completed). A 'partial fill' means only some of the requested shares were traded.", category: "Trading" },

  // Options & Derivatives
  { term: "Call Option", definition: "A contract giving the holder the right (not obligation) to buy an asset at a specified strike price before the expiration date.", category: "Options & Derivatives" },
  { term: "Put Option", definition: "A contract giving the holder the right (not obligation) to sell an asset at a specified strike price before the expiration date.", category: "Options & Derivatives" },
  { term: "Strike Price", definition: "The predetermined price at which an option can be exercised — the price at which you can buy (call) or sell (put) the underlying asset.", category: "Options & Derivatives" },
  { term: "Premium", definition: "The price paid to purchase an option contract. It represents the maximum loss for the buyer and maximum gain for the seller.", category: "Options & Derivatives" },
  { term: "Expiration Date", definition: "The last date an option can be exercised. After expiration, out-of-the-money options become worthless.", category: "Options & Derivatives" },
  { term: "In the Money (ITM)", definition: "A call option where the stock price is above the strike price, or a put where the stock is below the strike. The option has intrinsic value.", category: "Options & Derivatives" },
  { term: "Out of the Money (OTM)", definition: "A call option where the stock is below the strike, or a put where the stock is above the strike. No intrinsic value — only time value.", category: "Options & Derivatives" },
  { term: "Delta", definition: "Measures how much an option's price changes for a $1 move in the underlying asset. Call deltas range 0 to 1; put deltas -1 to 0.", category: "Options & Derivatives" },
  { term: "Theta", definition: "The rate of time decay — how much value an option loses per day as it approaches expiration, all else being equal.", category: "Options & Derivatives" },
  { term: "Implied Volatility (IV)", definition: "The market's expectation of future price movement magnitude, derived from option prices. Higher IV means more expensive options.", category: "Options & Derivatives" },
  { term: "Covered Call", definition: "Selling a call option while owning the underlying shares. Generates income (premium) but caps upside potential.", category: "Options & Derivatives" },
  { term: "Protective Put", definition: "Buying a put option while owning shares as insurance against a price drop. Limits downside risk at the cost of the premium.", category: "Options & Derivatives" },

  // Fixed Income
  { term: "Bond", definition: "A fixed-income debt instrument where the issuer borrows money from investors and promises to repay principal plus interest (coupon) over time.", category: "Fixed Income" },
  { term: "Coupon Rate", definition: "The annual interest rate paid by a bond issuer, expressed as a percentage of the bond's face value (par). Paid semiannually in most cases.", category: "Fixed Income" },
  { term: "Yield to Maturity (YTM)", definition: "The total return anticipated if a bond is held until it matures, accounting for coupon payments, par value, current price, and time remaining.", category: "Fixed Income" },
  { term: "Par Value (Face Value)", definition: "The nominal value of a bond (typically $1,000) that the issuer repays at maturity. Coupon payments are calculated as a percentage of par.", category: "Fixed Income" },
  { term: "Duration", definition: "A measure of a bond's sensitivity to interest rate changes. A duration of 5 means a 1% rate increase causes approximately a 5% price decline.", category: "Fixed Income" },
  { term: "Credit Rating", definition: "An assessment of a bond issuer's ability to repay debt (AAA = highest quality, D = default). Rated by agencies like S&P, Moody's, and Fitch.", category: "Fixed Income" },
  { term: "Yield Curve", definition: "A graph plotting bond yields across different maturities. Normally upward-sloping (longer maturity = higher yield). An inverted curve may signal recession.", category: "Fixed Income" },
  { term: "Treasury Bond", definition: "A U.S. government-issued bond with maturities of 10–30 years. Considered virtually risk-free, used as the benchmark for the risk-free rate.", category: "Fixed Income" },
  { term: "Junk Bond (High-Yield)", definition: "A bond rated below investment grade (BB+ or lower). Offers higher yields to compensate investors for the greater risk of default.", category: "Fixed Income" },
  { term: "Credit Spread", definition: "The yield difference between a corporate bond and a comparable government bond. Reflects the additional compensation for bearing credit risk.", category: "Fixed Income" },

  // Economics
  { term: "GDP (Gross Domestic Product)", definition: "The total value of all goods and services produced within a country over a specific period. The broadest measure of economic output and health.", category: "Economics" },
  { term: "Inflation", definition: "A sustained increase in the general price level of goods and services, reducing purchasing power. Measured by CPI and PCE indices.", category: "Economics" },
  { term: "Deflation", definition: "A sustained decrease in the general price level. While it increases purchasing power, it can signal economic weakness and suppress spending.", category: "Economics" },
  { term: "Interest Rate", definition: "The cost of borrowing money, set by central banks (like the Federal Reserve). Higher rates slow borrowing and spending; lower rates stimulate activity.", category: "Economics" },
  { term: "Federal Reserve (The Fed)", definition: "The central bank of the United States, responsible for monetary policy, interest rates, banking regulation, and financial system stability.", category: "Economics" },
  { term: "Fiscal Policy", definition: "Government decisions on taxation and spending to influence the economy. Expansionary policy increases spending; contractionary policy reduces it.", category: "Economics" },
  { term: "Monetary Policy", definition: "Central bank actions to control money supply and interest rates. Tools include the federal funds rate, open market operations, and reserve requirements.", category: "Economics" },
  { term: "Quantitative Easing (QE)", definition: "A central bank purchasing securities (usually bonds) to inject money into the economy, lower long-term rates, and stimulate economic activity.", category: "Economics" },
  { term: "CPI (Consumer Price Index)", definition: "A measure of the average change in prices paid by consumers for a basket of goods and services. The primary gauge of consumer inflation.", category: "Economics" },
  { term: "Recession", definition: "Commonly defined as two consecutive quarters of negative GDP growth. Characterized by declining output, rising unemployment, and reduced consumer spending.", category: "Economics" },
  { term: "Stagflation", definition: "A rare and challenging combination of stagnant economic growth, high unemployment, and high inflation occurring simultaneously.", category: "Economics" },
  { term: "Trade Deficit", definition: "When a country imports more goods and services than it exports. The difference represents net outflow of domestic currency to foreign markets.", category: "Economics" },

  // Portfolio Management
  { term: "Asset Allocation", definition: "The strategic distribution of investments among different asset classes (stocks, bonds, cash, real estate) based on risk tolerance, goals, and time horizon.", category: "Portfolio Management" },
  { term: "Diversification", definition: "Spreading investments across different assets, sectors, and geographies to reduce unsystematic risk. 'Don't put all your eggs in one basket.'", category: "Portfolio Management" },
  { term: "Rebalancing", definition: "Periodically adjusting portfolio weights back to target allocation by selling overweight and buying underweight positions to maintain desired risk profile.", category: "Portfolio Management" },
  { term: "Dollar-Cost Averaging", definition: "Investing a fixed dollar amount at regular intervals regardless of price. Reduces the impact of volatility by buying more shares when prices are low.", category: "Portfolio Management" },
  { term: "Modern Portfolio Theory (MPT)", definition: "A framework by Harry Markowitz for constructing portfolios that maximize expected return for a given level of risk using the efficient frontier.", category: "Portfolio Management" },
  { term: "Alpha", definition: "The excess return of a portfolio above a benchmark (like the S&P 500). Positive alpha = outperformance; negative alpha = underperformance.", category: "Portfolio Management" },
  { term: "Benchmark", definition: "A standard index (like S&P 500 or NASDAQ) used to compare portfolio performance. It answers: 'Did I beat the market?'", category: "Portfolio Management" },
  { term: "Index Fund", definition: "A passively managed fund that replicates a market index at low cost. Doesn't try to beat the market, just matches it. Popularized by Jack Bogle.", category: "Portfolio Management" },
  { term: "Active Management", definition: "A portfolio strategy where managers make specific investment decisions to outperform a benchmark, using research, market timing, and stock selection.", category: "Portfolio Management" },
  { term: "Passive Management", definition: "A strategy that tracks a market index with minimal trading and lower fees. Evidence shows most active managers underperform passive over long periods.", category: "Portfolio Management" },
  { term: "Tax-Loss Harvesting", definition: "Selling losing investments to offset capital gains and reduce tax liability, then potentially reinvesting in similar (but not identical) securities.", category: "Portfolio Management" },

  // Risk & Regulation
  { term: "Beta", definition: "A measure of a stock's volatility relative to the overall market. Beta > 1 = more volatile than market; < 1 = less volatile; 1 = moves with market.", category: "Risk & Regulation" },
  { term: "Sharpe Ratio", definition: "Risk-adjusted return: (Portfolio Return − Risk-Free Rate) ÷ Standard Deviation. Higher values indicate better return per unit of risk taken.", category: "Risk & Regulation" },
  { term: "Standard Deviation", definition: "A statistical measure of how much returns deviate from the average. Higher standard deviation = more volatility = more uncertainty.", category: "Risk & Regulation" },
  { term: "Systematic Risk", definition: "Market-wide risk affecting all investments (recessions, geopolitical events, interest rate changes). Cannot be diversified away.", category: "Risk & Regulation" },
  { term: "Unsystematic Risk", definition: "Risk specific to a company or industry (management changes, product recalls). Can be reduced through diversification.", category: "Risk & Regulation" },
  { term: "Value at Risk (VaR)", definition: "An estimate of the maximum potential loss of a portfolio over a given time period at a specified confidence level (e.g., 95%).", category: "Risk & Regulation" },
  { term: "Hedge", definition: "An investment made to reduce the risk of adverse price movements. Like insurance — limits potential losses but also caps some gains.", category: "Risk & Regulation" },
  { term: "SEC", definition: "The Securities and Exchange Commission — the U.S. federal agency that regulates securities markets, enforces laws, and protects investors from fraud.", category: "Risk & Regulation" },
  { term: "SEBI", definition: "The Securities and Exchange Board of India — the regulatory authority for the Indian securities market, similar to the SEC in the United States.", category: "Risk & Regulation" },
  { term: "Insider Trading", definition: "Illegal practice of trading securities based on material, non-public information. Undermines market fairness and is punishable by fines and imprisonment.", category: "Risk & Regulation" },
  { term: "Fiduciary Duty", definition: "A legal obligation to act in another party's best interest. Financial advisors with fiduciary duty must prioritize client interests above their own.", category: "Risk & Regulation" },
  { term: "KYC (Know Your Customer)", definition: "Regulatory requirements for financial institutions to verify client identity, assess risk, and prevent money laundering and fraud.", category: "Risk & Regulation" },
  { term: "Circuit Breaker", definition: "Automatic trading halts triggered when a major index falls by a specified percentage in a single day (7%, 13%, 20% for the S&P 500). Prevents panic selling.", category: "Risk & Regulation" },
  { term: "Capital Gains Tax", definition: "Tax on the profit from selling an investment. Short-term gains (held < 1 year) are taxed as ordinary income; long-term gains receive lower rates.", category: "Risk & Regulation" },
];
