export interface SearchItem {
  symbol: string;
  name: string;
  exchange: string;
}

export const STOCK_DATABASE: SearchItem[] = [
  // ═══════════════════════════════════════════
  // MEGA CAP TECH ($500B+)
  // ═══════════════════════════════════════════
  { symbol: "AAPL", name: "Apple Inc.", exchange: "NASDAQ" },
  { symbol: "MSFT", name: "Microsoft Corporation", exchange: "NASDAQ" },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)", exchange: "NASDAQ" },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)", exchange: "NASDAQ" },
  { symbol: "AMZN", name: "Amazon.com Inc.", exchange: "NASDAQ" },
  { symbol: "NVDA", name: "NVIDIA Corporation", exchange: "NASDAQ" },
  { symbol: "META", name: "Meta Platforms Inc.", exchange: "NASDAQ" },
  { symbol: "TSLA", name: "Tesla Inc.", exchange: "NASDAQ" },
  { symbol: "TSM", name: "Taiwan Semiconductor Manufacturing", exchange: "NYSE" },
  { symbol: "AVGO", name: "Broadcom Inc.", exchange: "NASDAQ" },
  { symbol: "ORCL", name: "Oracle Corporation", exchange: "NYSE" },
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc.", exchange: "NYSE" },
  { symbol: "BRK.A", name: "Berkshire Hathaway (Class A)", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // TECHNOLOGY — Software, Cloud, SaaS
  // ═══════════════════════════════════════════
  { symbol: "ADBE", name: "Adobe Inc.", exchange: "NASDAQ" },
  { symbol: "CRM", name: "Salesforce Inc.", exchange: "NYSE" },
  { symbol: "CSCO", name: "Cisco Systems Inc.", exchange: "NASDAQ" },
  { symbol: "ACN", name: "Accenture plc", exchange: "NYSE" },
  { symbol: "IBM", name: "International Business Machines", exchange: "NYSE" },
  { symbol: "INTC", name: "Intel Corporation", exchange: "NASDAQ" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc.", exchange: "NASDAQ" },
  { symbol: "QCOM", name: "Qualcomm Inc.", exchange: "NASDAQ" },
  { symbol: "TXN", name: "Texas Instruments Inc.", exchange: "NASDAQ" },
  { symbol: "NOW", name: "ServiceNow Inc.", exchange: "NYSE" },
  { symbol: "INTU", name: "Intuit Inc.", exchange: "NASDAQ" },
  { symbol: "AMAT", name: "Applied Materials Inc.", exchange: "NASDAQ" },
  { symbol: "LRCX", name: "Lam Research Corporation", exchange: "NASDAQ" },
  { symbol: "MU", name: "Micron Technology Inc.", exchange: "NASDAQ" },
  { symbol: "KLAC", name: "KLA Corporation", exchange: "NASDAQ" },
  { symbol: "SNPS", name: "Synopsys Inc.", exchange: "NASDAQ" },
  { symbol: "CDNS", name: "Cadence Design Systems", exchange: "NASDAQ" },
  { symbol: "PANW", name: "Palo Alto Networks Inc.", exchange: "NASDAQ" },
  { symbol: "CRWD", name: "CrowdStrike Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "NFLX", name: "Netflix Inc.", exchange: "NASDAQ" },
  { symbol: "UBER", name: "Uber Technologies Inc.", exchange: "NYSE" },
  { symbol: "SHOP", name: "Shopify Inc.", exchange: "NYSE" },
  { symbol: "SQ", name: "Block Inc.", exchange: "NYSE" },
  { symbol: "SPOT", name: "Spotify Technology S.A.", exchange: "NYSE" },
  { symbol: "SNAP", name: "Snap Inc.", exchange: "NYSE" },
  { symbol: "PINS", name: "Pinterest Inc.", exchange: "NYSE" },
  { symbol: "ROKU", name: "Roku Inc.", exchange: "NASDAQ" },
  { symbol: "ZM", name: "Zoom Video Communications", exchange: "NASDAQ" },
  { symbol: "DOCU", name: "DocuSign Inc.", exchange: "NASDAQ" },
  { symbol: "PLTR", name: "Palantir Technologies Inc.", exchange: "NYSE" },
  { symbol: "SNOW", name: "Snowflake Inc.", exchange: "NYSE" },
  { symbol: "DDOG", name: "Datadog Inc.", exchange: "NASDAQ" },
  { symbol: "NET", name: "Cloudflare Inc.", exchange: "NYSE" },
  { symbol: "TEAM", name: "Atlassian Corporation", exchange: "NASDAQ" },
  { symbol: "WDAY", name: "Workday Inc.", exchange: "NASDAQ" },
  { symbol: "ZS", name: "Zscaler Inc.", exchange: "NASDAQ" },
  { symbol: "OKTA", name: "Okta Inc.", exchange: "NASDAQ" },
  { symbol: "TWLO", name: "Twilio Inc.", exchange: "NYSE" },
  { symbol: "MDB", name: "MongoDB Inc.", exchange: "NASDAQ" },
  { symbol: "PATH", name: "UiPath Inc.", exchange: "NYSE" },
  { symbol: "TTD", name: "The Trade Desk Inc.", exchange: "NASDAQ" },
  { symbol: "ABNB", name: "Airbnb Inc.", exchange: "NASDAQ" },
  { symbol: "DASH", name: "DoorDash Inc.", exchange: "NASDAQ" },
  { symbol: "ADI", name: "Analog Devices Inc.", exchange: "NASDAQ" },
  { symbol: "MRVL", name: "Marvell Technology Inc.", exchange: "NASDAQ" },
  { symbol: "ON", name: "ON Semiconductor Corporation", exchange: "NASDAQ" },
  { symbol: "FTNT", name: "Fortinet Inc.", exchange: "NASDAQ" },
  { symbol: "ANSS", name: "ANSYS Inc.", exchange: "NASDAQ" },
  { symbol: "NXPI", name: "NXP Semiconductors N.V.", exchange: "NASDAQ" },
  { symbol: "SAP", name: "SAP SE", exchange: "NYSE" },
  { symbol: "ASML", name: "ASML Holding N.V.", exchange: "NASDAQ" },
  { symbol: "ARM", name: "Arm Holdings plc", exchange: "NASDAQ" },
  { symbol: "SMCI", name: "Super Micro Computer Inc.", exchange: "NASDAQ" },
  { symbol: "DELL", name: "Dell Technologies Inc.", exchange: "NYSE" },
  { symbol: "HPQ", name: "HP Inc.", exchange: "NYSE" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", exchange: "NYSE" },
  { symbol: "WDC", name: "Western Digital Corporation", exchange: "NASDAQ" },
  { symbol: "STX", name: "Seagate Technology Holdings", exchange: "NASDAQ" },
  { symbol: "NTAP", name: "NetApp Inc.", exchange: "NASDAQ" },
  { symbol: "KEYS", name: "Keysight Technologies Inc.", exchange: "NYSE" },
  { symbol: "TER", name: "Teradyne Inc.", exchange: "NASDAQ" },
  { symbol: "SWKS", name: "Skyworks Solutions Inc.", exchange: "NASDAQ" },
  { symbol: "MCHP", name: "Microchip Technology Inc.", exchange: "NASDAQ" },
  { symbol: "MPWR", name: "Monolithic Power Systems Inc.", exchange: "NASDAQ" },
  { symbol: "ENPH", name: "Enphase Energy Inc.", exchange: "NASDAQ" },
  { symbol: "SEDG", name: "SolarEdge Technologies Inc.", exchange: "NASDAQ" },
  { symbol: "FSLR", name: "First Solar Inc.", exchange: "NASDAQ" },
  { symbol: "WOLF", name: "Wolfspeed Inc.", exchange: "NYSE" },
  { symbol: "GLOB", name: "Globant S.A.", exchange: "NYSE" },
  { symbol: "EPAM", name: "EPAM Systems Inc.", exchange: "NYSE" },
  { symbol: "GDDY", name: "GoDaddy Inc.", exchange: "NYSE" },
  { symbol: "GEN", name: "Gen Digital Inc.", exchange: "NASDAQ" },
  { symbol: "RPD", name: "Rapid7 Inc.", exchange: "NASDAQ" },
  { symbol: "TENB", name: "Tenable Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "QLYS", name: "Qualys Inc.", exchange: "NASDAQ" },
  { symbol: "VRNS", name: "Varonis Systems Inc.", exchange: "NASDAQ" },
  { symbol: "S", name: "SentinelOne Inc.", exchange: "NYSE" },
  { symbol: "CFLT", name: "Confluent Inc.", exchange: "NASDAQ" },
  { symbol: "ESTC", name: "Elastic N.V.", exchange: "NYSE" },
  { symbol: "HUBS", name: "HubSpot Inc.", exchange: "NYSE" },
  { symbol: "PCTY", name: "Paylocity Holding Corporation", exchange: "NASDAQ" },
  { symbol: "PAYC", name: "Paycom Software Inc.", exchange: "NYSE" },
  { symbol: "WK", name: "Workiva Inc.", exchange: "NYSE" },
  { symbol: "BILL", name: "BILL Holdings Inc.", exchange: "NYSE" },
  { symbol: "QTWO", name: "Q2 Holdings Inc.", exchange: "NYSE" },
  { symbol: "ALTR", name: "Altair Engineering Inc.", exchange: "NASDAQ" },
  { symbol: "PTC", name: "PTC Inc.", exchange: "NASDAQ" },
  { symbol: "MANH", name: "Manhattan Associates Inc.", exchange: "NASDAQ" },
  { symbol: "SSNC", name: "SS&C Technologies Holdings", exchange: "NASDAQ" },
  { symbol: "TYL", name: "Tyler Technologies Inc.", exchange: "NYSE" },
  { symbol: "FFIV", name: "F5 Inc.", exchange: "NASDAQ" },
  { symbol: "AKAM", name: "Akamai Technologies Inc.", exchange: "NASDAQ" },
  { symbol: "JNPR", name: "Juniper Networks Inc.", exchange: "NYSE" },
  { symbol: "ZBRA", name: "Zebra Technologies Corporation", exchange: "NASDAQ" },
  { symbol: "CDW", name: "CDW Corporation", exchange: "NASDAQ" },
  { symbol: "NLOK", name: "NortonLifeLock Inc.", exchange: "NASDAQ" },
  { symbol: "CTSH", name: "Cognizant Technology Solutions", exchange: "NASDAQ" },
  { symbol: "LDOS", name: "Leidos Holdings Inc.", exchange: "NYSE" },
  { symbol: "SAIC", name: "Science Applications International", exchange: "NYSE" },
  { symbol: "BAH", name: "Booz Allen Hamilton Holding", exchange: "NYSE" },
  { symbol: "CACI", name: "CACI International Inc.", exchange: "NYSE" },
  { symbol: "DXC", name: "DXC Technology Company", exchange: "NYSE" },
  { symbol: "TOST", name: "Toast Inc.", exchange: "NYSE" },
  { symbol: "GLBE", name: "Global-e Online Ltd.", exchange: "NASDAQ" },
  { symbol: "BRZE", name: "Braze Inc.", exchange: "NASDAQ" },
  { symbol: "IOT", name: "Samsara Inc.", exchange: "NYSE" },
  { symbol: "APPS", name: "Digital Turbine Inc.", exchange: "NASDAQ" },
  { symbol: "FOUR", name: "Shift4 Payments Inc.", exchange: "NYSE" },
  { symbol: "RAMP", name: "LiveRamp Holdings Inc.", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // FINANCE — Banks, Insurance, Fintech
  // ═══════════════════════════════════════════
  { symbol: "JPM", name: "JPMorgan Chase & Co.", exchange: "NYSE" },
  { symbol: "V", name: "Visa Inc.", exchange: "NYSE" },
  { symbol: "MA", name: "Mastercard Inc.", exchange: "NYSE" },
  { symbol: "BAC", name: "Bank of America Corporation", exchange: "NYSE" },
  { symbol: "WFC", name: "Wells Fargo & Company", exchange: "NYSE" },
  { symbol: "GS", name: "The Goldman Sachs Group", exchange: "NYSE" },
  { symbol: "MS", name: "Morgan Stanley", exchange: "NYSE" },
  { symbol: "BLK", name: "BlackRock Inc.", exchange: "NYSE" },
  { symbol: "C", name: "Citigroup Inc.", exchange: "NYSE" },
  { symbol: "SCHW", name: "Charles Schwab Corporation", exchange: "NYSE" },
  { symbol: "AXP", name: "American Express Company", exchange: "NYSE" },
  { symbol: "SPGI", name: "S&P Global Inc.", exchange: "NYSE" },
  { symbol: "ICE", name: "Intercontinental Exchange", exchange: "NYSE" },
  { symbol: "CME", name: "CME Group Inc.", exchange: "NASDAQ" },
  { symbol: "MCO", name: "Moody's Corporation", exchange: "NYSE" },
  { symbol: "CB", name: "Chubb Limited", exchange: "NYSE" },
  { symbol: "MMC", name: "Marsh & McLennan Companies", exchange: "NYSE" },
  { symbol: "AON", name: "Aon plc", exchange: "NYSE" },
  { symbol: "PGR", name: "The Progressive Corporation", exchange: "NYSE" },
  { symbol: "TFC", name: "Truist Financial Corporation", exchange: "NYSE" },
  { symbol: "USB", name: "U.S. Bancorp", exchange: "NYSE" },
  { symbol: "PNC", name: "PNC Financial Services", exchange: "NYSE" },
  { symbol: "COF", name: "Capital One Financial", exchange: "NYSE" },
  { symbol: "BK", name: "The Bank of New York Mellon", exchange: "NYSE" },
  { symbol: "PYPL", name: "PayPal Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "FIS", name: "Fidelity National Information", exchange: "NYSE" },
  { symbol: "FISV", name: "Fiserv Inc.", exchange: "NYSE" },
  { symbol: "AIG", name: "American International Group", exchange: "NYSE" },
  { symbol: "MET", name: "MetLife Inc.", exchange: "NYSE" },
  { symbol: "PRU", name: "Prudential Financial Inc.", exchange: "NYSE" },
  { symbol: "ALL", name: "The Allstate Corporation", exchange: "NYSE" },
  { symbol: "TRV", name: "The Travelers Companies", exchange: "NYSE" },
  { symbol: "BX", name: "Blackstone Inc.", exchange: "NYSE" },
  { symbol: "KKR", name: "KKR & Co. Inc.", exchange: "NYSE" },
  { symbol: "APO", name: "Apollo Global Management", exchange: "NYSE" },
  { symbol: "ARES", name: "Ares Management Corporation", exchange: "NYSE" },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co.", exchange: "NYSE" },
  { symbol: "ACGL", name: "Arch Capital Group Ltd.", exchange: "NASDAQ" },
  { symbol: "AFL", name: "Aflac Incorporated", exchange: "NYSE" },
  { symbol: "HIG", name: "The Hartford Financial Services", exchange: "NYSE" },
  { symbol: "MSCI", name: "MSCI Inc.", exchange: "NYSE" },
  { symbol: "VRSK", name: "Verisk Analytics Inc.", exchange: "NASDAQ" },
  { symbol: "COIN", name: "Coinbase Global Inc.", exchange: "NASDAQ" },
  { symbol: "HOOD", name: "Robinhood Markets Inc.", exchange: "NASDAQ" },
  { symbol: "SOFI", name: "SoFi Technologies Inc.", exchange: "NASDAQ" },
  { symbol: "AFRM", name: "Affirm Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "UPST", name: "Upstart Holdings Inc.", exchange: "NASDAQ" },
  // Regional / Mid-Cap Banks
  { symbol: "MTB", name: "M&T Bank Corporation", exchange: "NYSE" },
  { symbol: "FITB", name: "Fifth Third Bancorp", exchange: "NASDAQ" },
  { symbol: "HBAN", name: "Huntington Bancshares", exchange: "NASDAQ" },
  { symbol: "KEY", name: "KeyCorp", exchange: "NYSE" },
  { symbol: "RF", name: "Regions Financial Corporation", exchange: "NYSE" },
  { symbol: "CFG", name: "Citizens Financial Group", exchange: "NYSE" },
  { symbol: "SIVB", name: "SVB Financial Group", exchange: "NASDAQ" },
  { symbol: "ZION", name: "Zions Bancorporation", exchange: "NASDAQ" },
  { symbol: "CMA", name: "Comerica Incorporated", exchange: "NYSE" },
  { symbol: "FRC", name: "First Republic Bank", exchange: "NYSE" },
  { symbol: "ALLY", name: "Ally Financial Inc.", exchange: "NYSE" },
  { symbol: "DFS", name: "Discover Financial Services", exchange: "NYSE" },
  { symbol: "SYF", name: "Synchrony Financial", exchange: "NYSE" },
  { symbol: "NDAQ", name: "Nasdaq Inc.", exchange: "NASDAQ" },
  { symbol: "CBOE", name: "Cboe Global Markets Inc.", exchange: "CBOE" },
  { symbol: "TROW", name: "T. Rowe Price Group Inc.", exchange: "NASDAQ" },
  { symbol: "IVZ", name: "Invesco Ltd.", exchange: "NYSE" },
  { symbol: "BEN", name: "Franklin Resources Inc.", exchange: "NYSE" },
  { symbol: "AMG", name: "Affiliated Managers Group", exchange: "NYSE" },
  { symbol: "LPLA", name: "LPL Financial Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "RJF", name: "Raymond James Financial", exchange: "NYSE" },
  { symbol: "NTRS", name: "Northern Trust Corporation", exchange: "NASDAQ" },
  { symbol: "STT", name: "State Street Corporation", exchange: "NYSE" },
  { symbol: "EWBC", name: "East West Bancorp Inc.", exchange: "NASDAQ" },
  { symbol: "FNB", name: "F.N.B. Corporation", exchange: "NYSE" },
  { symbol: "WAL", name: "Western Alliance Bancorporation", exchange: "NYSE" },
  { symbol: "PACW", name: "PacWest Bancorp", exchange: "NASDAQ" },
  { symbol: "SBNY", name: "Signature Bank", exchange: "NASDAQ" },
  { symbol: "FCNCA", name: "First Citizens BancShares", exchange: "NASDAQ" },
  { symbol: "WTFC", name: "Wintrust Financial Corporation", exchange: "NASDAQ" },
  { symbol: "UMBF", name: "UMB Financial Corporation", exchange: "NASDAQ" },
  { symbol: "SNV", name: "Synovus Financial Corp.", exchange: "NYSE" },
  { symbol: "BOKF", name: "BOK Financial Corporation", exchange: "NASDAQ" },
  { symbol: "FHN", name: "First Horizon Corporation", exchange: "NYSE" },
  { symbol: "WBS", name: "Webster Financial Corporation", exchange: "NYSE" },
  { symbol: "PNFP", name: "Pinnacle Financial Partners", exchange: "NASDAQ" },
  { symbol: "GBCI", name: "Glacier Bancorp Inc.", exchange: "NYSE" },
  { symbol: "CADE", name: "Cadence Bank", exchange: "NYSE" },
  { symbol: "OZK", name: "Bank OZK", exchange: "NASDAQ" },
  { symbol: "UBSI", name: "United Bankshares Inc.", exchange: "NASDAQ" },
  { symbol: "HWC", name: "Hancock Whitney Corporation", exchange: "NASDAQ" },
  { symbol: "SBCF", name: "Seacoast Banking Corp of Florida", exchange: "NASDAQ" },
  { symbol: "IBOC", name: "International Bancshares Corp", exchange: "NASDAQ" },
  { symbol: "FFIN", name: "First Financial Bankshares", exchange: "NASDAQ" },
  { symbol: "NYCB", name: "New York Community Bancorp", exchange: "NYSE" },
  // Insurance mid/small
  { symbol: "L", name: "Loews Corporation", exchange: "NYSE" },
  { symbol: "WRB", name: "W. R. Berkley Corporation", exchange: "NYSE" },
  { symbol: "RE", name: "Everest Group Ltd.", exchange: "NYSE" },
  { symbol: "RNR", name: "RenaissanceRe Holdings Ltd.", exchange: "NYSE" },
  { symbol: "CINF", name: "Cincinnati Financial Corporation", exchange: "NASDAQ" },
  { symbol: "EG", name: "Everest Group Ltd.", exchange: "NYSE" },
  { symbol: "KMPR", name: "Kemper Corporation", exchange: "NYSE" },
  { symbol: "KNSL", name: "Kingsdale Advisors Inc.", exchange: "NYSE" },
  { symbol: "ERIE", name: "Erie Indemnity Company", exchange: "NASDAQ" },
  { symbol: "RLI", name: "RLI Corp.", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // HEALTHCARE — Pharma, Biotech, MedTech
  // ═══════════════════════════════════════════
  { symbol: "UNH", name: "UnitedHealth Group Inc.", exchange: "NYSE" },
  { symbol: "JNJ", name: "Johnson & Johnson", exchange: "NYSE" },
  { symbol: "LLY", name: "Eli Lilly and Company", exchange: "NYSE" },
  { symbol: "NVO", name: "Novo Nordisk A/S", exchange: "NYSE" },
  { symbol: "MRK", name: "Merck & Co. Inc.", exchange: "NYSE" },
  { symbol: "ABBV", name: "AbbVie Inc.", exchange: "NYSE" },
  { symbol: "PFE", name: "Pfizer Inc.", exchange: "NYSE" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", exchange: "NYSE" },
  { symbol: "ABT", name: "Abbott Laboratories", exchange: "NYSE" },
  { symbol: "DHR", name: "Danaher Corporation", exchange: "NYSE" },
  { symbol: "BMY", name: "Bristol-Myers Squibb Company", exchange: "NYSE" },
  { symbol: "AMGN", name: "Amgen Inc.", exchange: "NASDAQ" },
  { symbol: "GILD", name: "Gilead Sciences Inc.", exchange: "NASDAQ" },
  { symbol: "ISRG", name: "Intuitive Surgical Inc.", exchange: "NASDAQ" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", exchange: "NASDAQ" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", exchange: "NASDAQ" },
  { symbol: "MDT", name: "Medtronic plc", exchange: "NYSE" },
  { symbol: "SYK", name: "Stryker Corporation", exchange: "NYSE" },
  { symbol: "BSX", name: "Boston Scientific Corporation", exchange: "NYSE" },
  { symbol: "ELV", name: "Elevance Health Inc.", exchange: "NYSE" },
  { symbol: "CI", name: "The Cigna Group", exchange: "NYSE" },
  { symbol: "HUM", name: "Humana Inc.", exchange: "NYSE" },
  { symbol: "CVS", name: "CVS Health Corporation", exchange: "NYSE" },
  { symbol: "MCK", name: "McKesson Corporation", exchange: "NYSE" },
  { symbol: "ZTS", name: "Zoetis Inc.", exchange: "NYSE" },
  { symbol: "BIIB", name: "Biogen Inc.", exchange: "NASDAQ" },
  { symbol: "MRNA", name: "Moderna Inc.", exchange: "NASDAQ" },
  { symbol: "ILMN", name: "Illumina Inc.", exchange: "NASDAQ" },
  { symbol: "GEHC", name: "GE HealthCare Technologies", exchange: "NASDAQ" },
  { symbol: "A", name: "Agilent Technologies Inc.", exchange: "NYSE" },
  { symbol: "IQV", name: "IQVIA Holdings Inc.", exchange: "NYSE" },
  { symbol: "IDXX", name: "IDEXX Laboratories Inc.", exchange: "NASDAQ" },
  { symbol: "DXCM", name: "DexCom Inc.", exchange: "NASDAQ" },
  { symbol: "AZN", name: "AstraZeneca PLC", exchange: "NASDAQ" },
  { symbol: "SNY", name: "Sanofi", exchange: "NASDAQ" },
  { symbol: "GSK", name: "GSK plc", exchange: "NYSE" },
  { symbol: "NVS", name: "Novartis AG", exchange: "NYSE" },
  { symbol: "BNTX", name: "BioNTech SE", exchange: "NASDAQ" },
  // Additional Healthcare
  { symbol: "EW", name: "Edwards Lifesciences Corp.", exchange: "NYSE" },
  { symbol: "BDX", name: "Becton Dickinson and Company", exchange: "NYSE" },
  { symbol: "BAX", name: "Baxter International Inc.", exchange: "NYSE" },
  { symbol: "RMD", name: "ResMed Inc.", exchange: "NYSE" },
  { symbol: "HOLX", name: "Hologic Inc.", exchange: "NASDAQ" },
  { symbol: "MTD", name: "Mettler-Toledo International", exchange: "NYSE" },
  { symbol: "WAT", name: "Waters Corporation", exchange: "NYSE" },
  { symbol: "COO", name: "The Cooper Companies Inc.", exchange: "NASDAQ" },
  { symbol: "ALGN", name: "Align Technology Inc.", exchange: "NASDAQ" },
  { symbol: "TFX", name: "Teleflex Incorporated", exchange: "NYSE" },
  { symbol: "PODD", name: "Insulet Corporation", exchange: "NASDAQ" },
  { symbol: "INSP", name: "Inspire Medical Systems Inc.", exchange: "NYSE" },
  { symbol: "HZNP", name: "Horizon Therapeutics plc", exchange: "NASDAQ" },
  { symbol: "SGEN", name: "Seagen Inc.", exchange: "NASDAQ" },
  { symbol: "ALNY", name: "Alnylam Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "EXAS", name: "Exact Sciences Corporation", exchange: "NASDAQ" },
  { symbol: "RARE", name: "Ultragenyx Pharmaceutical", exchange: "NASDAQ" },
  { symbol: "BMRN", name: "BioMarin Pharmaceutical Inc.", exchange: "NASDAQ" },
  { symbol: "NBIX", name: "Neurocrine Biosciences Inc.", exchange: "NASDAQ" },
  { symbol: "PCVX", name: "Vaxcyte Inc.", exchange: "NASDAQ" },
  { symbol: "SRPT", name: "Sarepta Therapeutics Inc.", exchange: "NASDAQ" },
  { symbol: "EXEL", name: "Exelixis Inc.", exchange: "NASDAQ" },
  { symbol: "JAZZ", name: "Jazz Pharmaceuticals plc", exchange: "NASDAQ" },
  { symbol: "UTHR", name: "United Therapeutics Corp.", exchange: "NASDAQ" },
  { symbol: "INCY", name: "Incyte Corporation", exchange: "NASDAQ" },
  { symbol: "MEDP", name: "Medpace Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "CRL", name: "Charles River Laboratories", exchange: "NYSE" },
  { symbol: "ICLR", name: "ICON plc", exchange: "NASDAQ" },
  { symbol: "TECH", name: "Bio-Techne Corporation", exchange: "NASDAQ" },
  { symbol: "HSIC", name: "Henry Schein Inc.", exchange: "NASDAQ" },
  { symbol: "CAH", name: "Cardinal Health Inc.", exchange: "NYSE" },
  { symbol: "ABC", name: "AmerisourceBergen Corporation", exchange: "NYSE" },
  { symbol: "CNC", name: "Centene Corporation", exchange: "NYSE" },
  { symbol: "MOH", name: "Molina Healthcare Inc.", exchange: "NYSE" },
  { symbol: "HCA", name: "HCA Healthcare Inc.", exchange: "NYSE" },
  { symbol: "THC", name: "Tenet Healthcare Corporation", exchange: "NYSE" },
  { symbol: "UHS", name: "Universal Health Services", exchange: "NYSE" },
  { symbol: "DVA", name: "DaVita Inc.", exchange: "NYSE" },
  { symbol: "VEEV", name: "Veeva Systems Inc.", exchange: "NYSE" },
  { symbol: "DOCS", name: "Doximity Inc.", exchange: "NYSE" },
  { symbol: "HIMS", name: "Hims & Hers Health Inc.", exchange: "NYSE" },
  { symbol: "OSCR", name: "Oscar Health Inc.", exchange: "NYSE" },
  { symbol: "RVMD", name: "Revolution Medicines Inc.", exchange: "NASDAQ" },
  { symbol: "CRNX", name: "Crinetics Pharmaceuticals", exchange: "NASDAQ" },
  { symbol: "KRYS", name: "Krystal Biotech Inc.", exchange: "NASDAQ" },

  // ═══════════════════════════════════════════
  // CONSUMER DISCRETIONARY — Retail, Auto, Travel
  // ═══════════════════════════════════════════
  { symbol: "WMT", name: "Walmart Inc.", exchange: "NYSE" },
  { symbol: "HD", name: "The Home Depot Inc.", exchange: "NYSE" },
  { symbol: "MCD", name: "McDonald's Corporation", exchange: "NYSE" },
  { symbol: "NKE", name: "NIKE Inc.", exchange: "NYSE" },
  { symbol: "SBUX", name: "Starbucks Corporation", exchange: "NASDAQ" },
  { symbol: "TGT", name: "Target Corporation", exchange: "NYSE" },
  { symbol: "LOW", name: "Lowe's Companies Inc.", exchange: "NYSE" },
  { symbol: "DIS", name: "The Walt Disney Company", exchange: "NYSE" },
  { symbol: "BKNG", name: "Booking Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "TJX", name: "The TJX Companies Inc.", exchange: "NYSE" },
  { symbol: "CMG", name: "Chipotle Mexican Grill", exchange: "NYSE" },
  { symbol: "YUM", name: "Yum! Brands Inc.", exchange: "NYSE" },
  { symbol: "LULU", name: "Lululemon Athletica Inc.", exchange: "NASDAQ" },
  { symbol: "ROST", name: "Ross Stores Inc.", exchange: "NASDAQ" },
  { symbol: "DG", name: "Dollar General Corporation", exchange: "NYSE" },
  { symbol: "DLTR", name: "Dollar Tree Inc.", exchange: "NASDAQ" },
  { symbol: "COST", name: "Costco Wholesale Corporation", exchange: "NASDAQ" },
  { symbol: "ORLY", name: "O'Reilly Automotive Inc.", exchange: "NASDAQ" },
  { symbol: "AZO", name: "AutoZone Inc.", exchange: "NYSE" },
  { symbol: "AAP", name: "Advance Auto Parts Inc.", exchange: "NYSE" },
  { symbol: "TSCO", name: "Tractor Supply Company", exchange: "NASDAQ" },
  { symbol: "ULTA", name: "Ulta Beauty Inc.", exchange: "NASDAQ" },
  { symbol: "BBY", name: "Best Buy Co. Inc.", exchange: "NYSE" },
  { symbol: "EBAY", name: "eBay Inc.", exchange: "NASDAQ" },
  { symbol: "ETSY", name: "Etsy Inc.", exchange: "NASDAQ" },
  { symbol: "W", name: "Wayfair Inc.", exchange: "NYSE" },
  { symbol: "CHWY", name: "Chewy Inc.", exchange: "NYSE" },
  { symbol: "FIVE", name: "Five Below Inc.", exchange: "NASDAQ" },
  { symbol: "DECK", name: "Deckers Outdoor Corporation", exchange: "NYSE" },
  { symbol: "CROX", name: "Crocs Inc.", exchange: "NASDAQ" },
  { symbol: "BIRK", name: "Birkenstock Holding plc", exchange: "NYSE" },
  { symbol: "ON", name: "On Holding AG", exchange: "NYSE" },
  { symbol: "SKX", name: "Skechers U.S.A. Inc.", exchange: "NYSE" },
  { symbol: "VFC", name: "V.F. Corporation", exchange: "NYSE" },
  { symbol: "PVH", name: "PVH Corp.", exchange: "NYSE" },
  { symbol: "TPR", name: "Tapestry Inc.", exchange: "NYSE" },
  { symbol: "CPRI", name: "Capri Holdings Limited", exchange: "NYSE" },
  { symbol: "RL", name: "Ralph Lauren Corporation", exchange: "NYSE" },
  { symbol: "HBI", name: "Hanesbrands Inc.", exchange: "NYSE" },
  { symbol: "UAA", name: "Under Armour Inc. (Class A)", exchange: "NYSE" },
  { symbol: "GPS", name: "Gap Inc.", exchange: "NYSE" },
  { symbol: "ANF", name: "Abercrombie & Fitch Co.", exchange: "NYSE" },
  { symbol: "AEO", name: "American Eagle Outfitters Inc.", exchange: "NYSE" },
  { symbol: "URBN", name: "Urban Outfitters Inc.", exchange: "NASDAQ" },
  { symbol: "FL", name: "Foot Locker Inc.", exchange: "NYSE" },
  { symbol: "GME", name: "GameStop Corp.", exchange: "NYSE" },
  { symbol: "BBWI", name: "Bath & Body Works Inc.", exchange: "NYSE" },
  { symbol: "WSM", name: "Williams-Sonoma Inc.", exchange: "NYSE" },
  { symbol: "RH", name: "RH (Restoration Hardware)", exchange: "NYSE" },
  { symbol: "BURL", name: "Burlington Stores Inc.", exchange: "NYSE" },
  { symbol: "KSS", name: "Kohl's Corporation", exchange: "NYSE" },
  { symbol: "M", name: "Macy's Inc.", exchange: "NYSE" },
  { symbol: "JWN", name: "Nordstrom Inc.", exchange: "NYSE" },
  { symbol: "DKS", name: "DICK'S Sporting Goods Inc.", exchange: "NYSE" },
  { symbol: "CAVA", name: "CAVA Group Inc.", exchange: "NYSE" },
  { symbol: "SHAK", name: "Shake Shack Inc.", exchange: "NYSE" },
  { symbol: "WING", name: "Wingstop Inc.", exchange: "NASDAQ" },
  { symbol: "CARG", name: "CarGurus Inc.", exchange: "NASDAQ" },
  { symbol: "VRM", name: "Vroom Inc.", exchange: "NASDAQ" },
  { symbol: "CVNA", name: "Carvana Co.", exchange: "NYSE" },
  { symbol: "KMX", name: "CarMax Inc.", exchange: "NYSE" },
  { symbol: "LAD", name: "Lithia Motors Inc.", exchange: "NYSE" },
  { symbol: "AN", name: "AutoNation Inc.", exchange: "NYSE" },
  { symbol: "PAG", name: "Penske Automotive Group", exchange: "NYSE" },
  { symbol: "SAH", name: "Sonic Automotive Inc.", exchange: "NYSE" },
  { symbol: "GPI", name: "Group 1 Automotive Inc.", exchange: "NYSE" },
  { symbol: "ABG", name: "Asbury Automotive Group Inc.", exchange: "NYSE" },
  { symbol: "DENN", name: "Denny's Corporation", exchange: "NASDAQ" },
  { symbol: "DIN", name: "Dine Brands Global Inc.", exchange: "NYSE" },
  { symbol: "DRI", name: "Darden Restaurants Inc.", exchange: "NYSE" },
  { symbol: "EAT", name: "Brinker International Inc.", exchange: "NYSE" },
  { symbol: "TXRH", name: "Texas Roadhouse Inc.", exchange: "NASDAQ" },
  { symbol: "CAKE", name: "The Cheesecake Factory Inc.", exchange: "NASDAQ" },
  { symbol: "JACK", name: "Jack in the Box Inc.", exchange: "NASDAQ" },
  { symbol: "WEN", name: "The Wendy's Company", exchange: "NASDAQ" },
  { symbol: "QSR", name: "Restaurant Brands International", exchange: "NYSE" },
  { symbol: "SBUX", name: "Starbucks Corporation", exchange: "NASDAQ" },
  { symbol: "DPZ", name: "Domino's Pizza Inc.", exchange: "NYSE" },
  { symbol: "PZZA", name: "Papa John's International", exchange: "NASDAQ" },

  // Auto & EV
  { symbol: "TM", name: "Toyota Motor Corporation", exchange: "NYSE" },
  { symbol: "F", name: "Ford Motor Company", exchange: "NYSE" },
  { symbol: "GM", name: "General Motors Company", exchange: "NYSE" },
  { symbol: "STLA", name: "Stellantis N.V.", exchange: "NYSE" },
  { symbol: "HMC", name: "Honda Motor Co. Ltd.", exchange: "NYSE" },
  { symbol: "RIVN", name: "Rivian Automotive Inc.", exchange: "NASDAQ" },
  { symbol: "LCID", name: "Lucid Group Inc.", exchange: "NASDAQ" },
  { symbol: "NIO", name: "NIO Inc.", exchange: "NYSE" },
  { symbol: "XPEV", name: "XPeng Inc.", exchange: "NYSE" },
  { symbol: "LI", name: "Li Auto Inc.", exchange: "NASDAQ" },
  { symbol: "VNE", name: "Veoneer Inc.", exchange: "NYSE" },
  { symbol: "APTV", name: "Aptiv PLC", exchange: "NYSE" },
  { symbol: "BWA", name: "BorgWarner Inc.", exchange: "NYSE" },
  { symbol: "LEA", name: "Lear Corporation", exchange: "NYSE" },
  { symbol: "MGA", name: "Magna International Inc.", exchange: "NYSE" },
  { symbol: "ALV", name: "Autoliv Inc.", exchange: "NYSE" },
  { symbol: "THRM", name: "Gentherm Incorporated", exchange: "NASDAQ" },
  { symbol: "GTX", name: "Garrett Motion Inc.", exchange: "NASDAQ" },
  { symbol: "GOEV", name: "Canoo Inc.", exchange: "NASDAQ" },
  { symbol: "RIDE", name: "Lordstown Motors Corp.", exchange: "NASDAQ" },
  { symbol: "FSR", name: "Fisker Inc.", exchange: "NYSE" },
  { symbol: "PSNY", name: "Polestar Automotive Holding", exchange: "NASDAQ" },
  { symbol: "NKLA", name: "Nikola Corporation", exchange: "NASDAQ" },
  { symbol: "WKHS", name: "Workhorse Group Inc.", exchange: "NASDAQ" },
  { symbol: "HYLN", name: "Hyliion Holdings Corp.", exchange: "NYSE" },
  { symbol: "LAZR", name: "Luminar Technologies Inc.", exchange: "NASDAQ" },
  { symbol: "MVIS", name: "MicroVision Inc.", exchange: "NASDAQ" },
  { symbol: "QS", name: "QuantumScape Corporation", exchange: "NYSE" },

  // Car Rental, Fleet, Services
  { symbol: "CAR", name: "Avis Budget Group Inc.", exchange: "NASDAQ" },
  { symbol: "HTZ", name: "Hertz Global Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "URI", name: "United Rentals Inc.", exchange: "NYSE" },
  { symbol: "GATX", name: "GATX Corporation", exchange: "NYSE" },

  // Airlines & Travel
  { symbol: "DAL", name: "Delta Air Lines Inc.", exchange: "NYSE" },
  { symbol: "UAL", name: "United Airlines Holdings", exchange: "NASDAQ" },
  { symbol: "LUV", name: "Southwest Airlines Co.", exchange: "NYSE" },
  { symbol: "AAL", name: "American Airlines Group", exchange: "NASDAQ" },
  { symbol: "ALK", name: "Alaska Air Group Inc.", exchange: "NYSE" },
  { symbol: "JBLU", name: "JetBlue Airways Corporation", exchange: "NASDAQ" },
  { symbol: "SAVE", name: "Spirit Airlines Inc.", exchange: "NYSE" },
  { symbol: "HA", name: "Hawaiian Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "SKYW", name: "SkyWest Inc.", exchange: "NASDAQ" },
  { symbol: "MAR", name: "Marriott International", exchange: "NASDAQ" },
  { symbol: "HLT", name: "Hilton Worldwide Holdings", exchange: "NYSE" },
  { symbol: "H", name: "Hyatt Hotels Corporation", exchange: "NYSE" },
  { symbol: "WH", name: "Wyndham Hotels & Resorts", exchange: "NYSE" },
  { symbol: "CHH", name: "Choice Hotels International", exchange: "NYSE" },
  { symbol: "RCL", name: "Royal Caribbean Cruises", exchange: "NYSE" },
  { symbol: "CCL", name: "Carnival Corporation", exchange: "NYSE" },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings", exchange: "NYSE" },
  { symbol: "EXPE", name: "Expedia Group Inc.", exchange: "NASDAQ" },
  { symbol: "TRIP", name: "Tripadvisor Inc.", exchange: "NASDAQ" },
  { symbol: "MMYT", name: "MakeMyTrip Limited", exchange: "NASDAQ" },

  // ═══════════════════════════════════════════
  // CONSUMER STAPLES — Food, Beverage, Household
  // ═══════════════════════════════════════════
  { symbol: "PG", name: "Procter & Gamble Company", exchange: "NYSE" },
  { symbol: "KO", name: "The Coca-Cola Company", exchange: "NYSE" },
  { symbol: "PEP", name: "PepsiCo Inc.", exchange: "NASDAQ" },
  { symbol: "PM", name: "Philip Morris International", exchange: "NYSE" },
  { symbol: "MO", name: "Altria Group Inc.", exchange: "NYSE" },
  { symbol: "EL", name: "The Estée Lauder Companies", exchange: "NYSE" },
  { symbol: "CL", name: "Colgate-Palmolive Company", exchange: "NYSE" },
  { symbol: "KMB", name: "Kimberly-Clark Corporation", exchange: "NYSE" },
  { symbol: "GIS", name: "General Mills Inc.", exchange: "NYSE" },
  { symbol: "K", name: "Kellanova", exchange: "NYSE" },
  { symbol: "HSY", name: "The Hershey Company", exchange: "NYSE" },
  { symbol: "MDLZ", name: "Mondelez International", exchange: "NASDAQ" },
  { symbol: "STZ", name: "Constellation Brands Inc.", exchange: "NYSE" },
  { symbol: "BUD", name: "Anheuser-Busch InBev SA", exchange: "NYSE" },
  { symbol: "TAP", name: "Molson Coors Beverage Company", exchange: "NYSE" },
  { symbol: "SAM", name: "Boston Beer Company Inc.", exchange: "NYSE" },
  { symbol: "MNST", name: "Monster Beverage Corporation", exchange: "NASDAQ" },
  { symbol: "CELH", name: "Celsius Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "KDP", name: "Keurig Dr Pepper Inc.", exchange: "NASDAQ" },
  { symbol: "SJM", name: "The J.M. Smucker Company", exchange: "NYSE" },
  { symbol: "CPB", name: "Campbell Soup Company", exchange: "NYSE" },
  { symbol: "HRL", name: "Hormel Foods Corporation", exchange: "NYSE" },
  { symbol: "TSN", name: "Tyson Foods Inc.", exchange: "NYSE" },
  { symbol: "CAG", name: "Conagra Brands Inc.", exchange: "NYSE" },
  { symbol: "SFD", name: "Smithfield Foods Inc.", exchange: "NYSE" },
  { symbol: "KR", name: "The Kroger Co.", exchange: "NYSE" },
  { symbol: "SYY", name: "Sysco Corporation", exchange: "NYSE" },
  { symbol: "USFD", name: "US Foods Holding Corp.", exchange: "NYSE" },
  { symbol: "ADM", name: "Archer-Daniels-Midland Co.", exchange: "NYSE" },
  { symbol: "BG", name: "Bunge Global SA", exchange: "NYSE" },
  { symbol: "CLX", name: "The Clorox Company", exchange: "NYSE" },
  { symbol: "CHD", name: "Church & Dwight Co. Inc.", exchange: "NYSE" },
  { symbol: "SPB", name: "Spectrum Brands Holdings", exchange: "NYSE" },
  { symbol: "COTY", name: "Coty Inc.", exchange: "NYSE" },
  { symbol: "WBA", name: "Walgreens Boots Alliance Inc.", exchange: "NASDAQ" },

  // ═══════════════════════════════════════════
  // INDUSTRIALS — Aerospace, Defense, Manufacturing
  // ═══════════════════════════════════════════
  { symbol: "CAT", name: "Caterpillar Inc.", exchange: "NYSE" },
  { symbol: "DE", name: "Deere & Company", exchange: "NYSE" },
  { symbol: "UNP", name: "Union Pacific Corporation", exchange: "NYSE" },
  { symbol: "HON", name: "Honeywell International", exchange: "NASDAQ" },
  { symbol: "UPS", name: "United Parcel Service Inc.", exchange: "NYSE" },
  { symbol: "RTX", name: "RTX Corporation", exchange: "NYSE" },
  { symbol: "BA", name: "The Boeing Company", exchange: "NYSE" },
  { symbol: "LMT", name: "Lockheed Martin Corporation", exchange: "NYSE" },
  { symbol: "GE", name: "GE Aerospace", exchange: "NYSE" },
  { symbol: "MMM", name: "3M Company", exchange: "NYSE" },
  { symbol: "GD", name: "General Dynamics Corporation", exchange: "NYSE" },
  { symbol: "NOC", name: "Northrop Grumman Corporation", exchange: "NYSE" },
  { symbol: "FDX", name: "FedEx Corporation", exchange: "NYSE" },
  { symbol: "EMR", name: "Emerson Electric Co.", exchange: "NYSE" },
  { symbol: "ETN", name: "Eaton Corporation plc", exchange: "NYSE" },
  { symbol: "ITW", name: "Illinois Tool Works Inc.", exchange: "NYSE" },
  { symbol: "WM", name: "Waste Management Inc.", exchange: "NYSE" },
  { symbol: "RSG", name: "Republic Services Inc.", exchange: "NYSE" },
  { symbol: "CPRT", name: "Copart Inc.", exchange: "NASDAQ" },
  { symbol: "ODFL", name: "Old Dominion Freight Line", exchange: "NASDAQ" },
  { symbol: "FAST", name: "Fastenal Company", exchange: "NASDAQ" },
  { symbol: "CTAS", name: "Cintas Corporation", exchange: "NASDAQ" },
  { symbol: "ADP", name: "Automatic Data Processing", exchange: "NASDAQ" },
  { symbol: "PAYX", name: "Paychex Inc.", exchange: "NASDAQ" },
  { symbol: "CARR", name: "Carrier Global Corporation", exchange: "NYSE" },
  { symbol: "TT", name: "Trane Technologies plc", exchange: "NYSE" },
  { symbol: "PH", name: "Parker-Hannifin Corporation", exchange: "NYSE" },
  { symbol: "ROK", name: "Rockwell Automation Inc.", exchange: "NYSE" },
  { symbol: "OTIS", name: "Otis Worldwide Corporation", exchange: "NYSE" },
  { symbol: "AME", name: "AMETEK Inc.", exchange: "NYSE" },
  { symbol: "CMI", name: "Cummins Inc.", exchange: "NYSE" },
  { symbol: "PCAR", name: "PACCAR Inc.", exchange: "NASDAQ" },
  { symbol: "NSC", name: "Norfolk Southern Corporation", exchange: "NYSE" },
  { symbol: "CSX", name: "CSX Corporation", exchange: "NASDAQ" },
  { symbol: "IT", name: "Gartner Inc.", exchange: "NYSE" },
  { symbol: "IR", name: "Ingersoll Rand Inc.", exchange: "NYSE" },
  { symbol: "DOV", name: "Dover Corporation", exchange: "NYSE" },
  { symbol: "XYL", name: "Xylem Inc.", exchange: "NYSE" },
  { symbol: "GNRC", name: "Generac Holdings Inc.", exchange: "NYSE" },
  { symbol: "SWK", name: "Stanley Black & Decker Inc.", exchange: "NYSE" },
  { symbol: "NDSN", name: "Nordson Corporation", exchange: "NASDAQ" },
  { symbol: "IEX", name: "IDEX Corporation", exchange: "NYSE" },
  { symbol: "ROP", name: "Roper Technologies Inc.", exchange: "NASDAQ" },
  { symbol: "GWW", name: "W.W. Grainger Inc.", exchange: "NYSE" },
  { symbol: "SNA", name: "Snap-on Incorporated", exchange: "NYSE" },
  { symbol: "J", name: "Jacobs Solutions Inc.", exchange: "NYSE" },
  { symbol: "PWR", name: "Quanta Services Inc.", exchange: "NYSE" },
  { symbol: "EME", name: "EMCOR Group Inc.", exchange: "NYSE" },
  { symbol: "FIX", name: "Comfort Systems USA Inc.", exchange: "NYSE" },
  { symbol: "TTC", name: "The Toro Company", exchange: "NYSE" },
  { symbol: "HWM", name: "Howmet Aerospace Inc.", exchange: "NYSE" },
  { symbol: "TDG", name: "TransDigm Group Inc.", exchange: "NYSE" },
  { symbol: "HEI", name: "HEICO Corporation", exchange: "NYSE" },
  { symbol: "SPR", name: "Spirit AeroSystems Holdings", exchange: "NYSE" },
  { symbol: "TXT", name: "Textron Inc.", exchange: "NYSE" },
  { symbol: "LHX", name: "L3Harris Technologies Inc.", exchange: "NYSE" },
  { symbol: "HII", name: "Huntington Ingalls Industries", exchange: "NYSE" },
  { symbol: "AXON", name: "Axon Enterprise Inc.", exchange: "NASDAQ" },
  { symbol: "WCN", name: "Waste Connections Inc.", exchange: "NYSE" },
  { symbol: "UBER", name: "Uber Technologies Inc.", exchange: "NYSE" },
  { symbol: "LYFT", name: "Lyft Inc.", exchange: "NASDAQ" },
  { symbol: "XPO", name: "XPO Inc.", exchange: "NYSE" },
  { symbol: "JBHT", name: "J.B. Hunt Transport Services", exchange: "NASDAQ" },
  { symbol: "CHRW", name: "C.H. Robinson Worldwide Inc.", exchange: "NASDAQ" },
  { symbol: "EXPD", name: "Expeditors International", exchange: "NASDAQ" },
  { symbol: "SNDR", name: "Schneider National Inc.", exchange: "NYSE" },
  { symbol: "R", name: "Ryder System Inc.", exchange: "NYSE" },
  { symbol: "LSTR", name: "Landstar System Inc.", exchange: "NASDAQ" },
  { symbol: "KEX", name: "Kirby Corporation", exchange: "NYSE" },
  { symbol: "MATX", name: "Matson Inc.", exchange: "NYSE" },
  { symbol: "RXO", name: "RXO Inc.", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // ENERGY — Oil, Gas, Renewable
  // ═══════════════════════════════════════════
  { symbol: "XOM", name: "Exxon Mobil Corporation", exchange: "NYSE" },
  { symbol: "CVX", name: "Chevron Corporation", exchange: "NYSE" },
  { symbol: "COP", name: "ConocoPhillips", exchange: "NYSE" },
  { symbol: "SLB", name: "Schlumberger Limited", exchange: "NYSE" },
  { symbol: "EOG", name: "EOG Resources Inc.", exchange: "NYSE" },
  { symbol: "MPC", name: "Marathon Petroleum Corporation", exchange: "NYSE" },
  { symbol: "PSX", name: "Phillips 66", exchange: "NYSE" },
  { symbol: "VLO", name: "Valero Energy Corporation", exchange: "NYSE" },
  { symbol: "OXY", name: "Occidental Petroleum", exchange: "NYSE" },
  { symbol: "PXD", name: "Pioneer Natural Resources", exchange: "NYSE" },
  { symbol: "HAL", name: "Halliburton Company", exchange: "NYSE" },
  { symbol: "DVN", name: "Devon Energy Corporation", exchange: "NYSE" },
  { symbol: "FANG", name: "Diamondback Energy Inc.", exchange: "NASDAQ" },
  { symbol: "BKR", name: "Baker Hughes Company", exchange: "NASDAQ" },
  { symbol: "WMB", name: "The Williams Companies Inc.", exchange: "NYSE" },
  { symbol: "KMI", name: "Kinder Morgan Inc.", exchange: "NYSE" },
  { symbol: "OKE", name: "ONEOK Inc.", exchange: "NYSE" },
  { symbol: "ET", name: "Energy Transfer LP", exchange: "NYSE" },
  { symbol: "EPD", name: "Enterprise Products Partners", exchange: "NYSE" },
  { symbol: "MPLX", name: "MPLX LP", exchange: "NYSE" },
  { symbol: "LNG", name: "Cheniere Energy Inc.", exchange: "NYSE" },
  { symbol: "TRGP", name: "Targa Resources Corp.", exchange: "NYSE" },
  { symbol: "MRO", name: "Marathon Oil Corporation", exchange: "NYSE" },
  { symbol: "APA", name: "APA Corporation", exchange: "NASDAQ" },
  { symbol: "HES", name: "Hess Corporation", exchange: "NYSE" },
  { symbol: "CTRA", name: "Coterra Energy Inc.", exchange: "NYSE" },
  { symbol: "EQT", name: "EQT Corporation", exchange: "NYSE" },
  { symbol: "AR", name: "Antero Resources Corporation", exchange: "NYSE" },
  { symbol: "RRC", name: "Range Resources Corporation", exchange: "NYSE" },
  { symbol: "SWN", name: "Southwestern Energy Company", exchange: "NYSE" },
  { symbol: "CHK", name: "Chesapeake Energy Corporation", exchange: "NASDAQ" },
  { symbol: "PR", name: "Permian Resources Corporation", exchange: "NYSE" },
  { symbol: "CHRD", name: "Chord Energy Corporation", exchange: "NASDAQ" },
  { symbol: "MTDR", name: "Matador Resources Company", exchange: "NYSE" },
  { symbol: "SM", name: "SM Energy Company", exchange: "NYSE" },
  { symbol: "OVV", name: "Ovintiv Inc.", exchange: "NYSE" },
  { symbol: "MGY", name: "Magnolia Oil & Gas Corporation", exchange: "NYSE" },
  { symbol: "VTLE", name: "Vital Energy Inc.", exchange: "NYSE" },
  { symbol: "NOV", name: "NOV Inc.", exchange: "NYSE" },
  { symbol: "FTI", name: "TechnipFMC plc", exchange: "NYSE" },
  { symbol: "HP", name: "Helmerich & Payne Inc.", exchange: "NYSE" },
  { symbol: "RIG", name: "Transocean Ltd.", exchange: "NYSE" },
  { symbol: "DO", name: "Diamond Offshore Drilling", exchange: "NYSE" },
  { symbol: "NE", name: "Noble Corporation plc", exchange: "NYSE" },
  { symbol: "VAL", name: "Valaris Limited", exchange: "NYSE" },
  { symbol: "TTE", name: "TotalEnergies SE", exchange: "NYSE" },
  { symbol: "SHEL", name: "Shell plc", exchange: "NYSE" },
  { symbol: "BP", name: "BP p.l.c.", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // REAL ESTATE — REITs
  // ═══════════════════════════════════════════
  { symbol: "AMT", name: "American Tower Corporation", exchange: "NYSE" },
  { symbol: "PLD", name: "Prologis Inc.", exchange: "NYSE" },
  { symbol: "CCI", name: "Crown Castle Inc.", exchange: "NYSE" },
  { symbol: "EQIX", name: "Equinix Inc.", exchange: "NASDAQ" },
  { symbol: "PSA", name: "Public Storage", exchange: "NYSE" },
  { symbol: "SPG", name: "Simon Property Group", exchange: "NYSE" },
  { symbol: "O", name: "Realty Income Corporation", exchange: "NYSE" },
  { symbol: "DLR", name: "Digital Realty Trust", exchange: "NYSE" },
  { symbol: "WELL", name: "Welltower Inc.", exchange: "NYSE" },
  { symbol: "AVB", name: "AvalonBay Communities Inc.", exchange: "NYSE" },
  { symbol: "EQR", name: "Equity Residential", exchange: "NYSE" },
  { symbol: "VTR", name: "Ventas Inc.", exchange: "NYSE" },
  { symbol: "ARE", name: "Alexandria Real Estate Equities", exchange: "NYSE" },
  { symbol: "MAA", name: "Mid-America Apartment Communities", exchange: "NYSE" },
  { symbol: "UDR", name: "UDR Inc.", exchange: "NYSE" },
  { symbol: "ESS", name: "Essex Property Trust Inc.", exchange: "NYSE" },
  { symbol: "CPT", name: "Camden Property Trust", exchange: "NYSE" },
  { symbol: "INVH", name: "Invitation Homes Inc.", exchange: "NYSE" },
  { symbol: "SUI", name: "Sun Communities Inc.", exchange: "NYSE" },
  { symbol: "ELS", name: "Equity LifeStyle Properties", exchange: "NYSE" },
  { symbol: "REG", name: "Regency Centers Corporation", exchange: "NASDAQ" },
  { symbol: "FRT", name: "Federal Realty Investment Trust", exchange: "NYSE" },
  { symbol: "KIM", name: "Kimco Realty Corporation", exchange: "NYSE" },
  { symbol: "BXP", name: "BXP Inc.", exchange: "NYSE" },
  { symbol: "VNO", name: "Vornado Realty Trust", exchange: "NYSE" },
  { symbol: "SLG", name: "SL Green Realty Corp.", exchange: "NYSE" },
  { symbol: "HST", name: "Host Hotels & Resorts Inc.", exchange: "NASDAQ" },
  { symbol: "PEAK", name: "Healthpeak Properties Inc.", exchange: "NYSE" },
  { symbol: "MPW", name: "Medical Properties Trust Inc.", exchange: "NYSE" },
  { symbol: "IRM", name: "Iron Mountain Incorporated", exchange: "NYSE" },
  { symbol: "SBAC", name: "SBA Communications Corporation", exchange: "NASDAQ" },
  { symbol: "GLPI", name: "Gaming and Leisure Properties", exchange: "NASDAQ" },
  { symbol: "VICI", name: "VICI Properties Inc.", exchange: "NYSE" },
  { symbol: "NNN", name: "NNN REIT Inc.", exchange: "NYSE" },
  { symbol: "WPC", name: "W. P. Carey Inc.", exchange: "NYSE" },
  { symbol: "STOR", name: "STORE Capital Corporation", exchange: "NYSE" },
  { symbol: "STAG", name: "STAG Industrial Inc.", exchange: "NYSE" },
  { symbol: "CUBE", name: "CubeSmart", exchange: "NYSE" },
  { symbol: "EXR", name: "Extra Space Storage Inc.", exchange: "NYSE" },
  { symbol: "LSI", name: "Life Storage Inc.", exchange: "NYSE" },
  { symbol: "NSA", name: "National Storage Affiliates Trust", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // UTILITIES
  // ═══════════════════════════════════════════
  { symbol: "NEE", name: "NextEra Energy Inc.", exchange: "NYSE" },
  { symbol: "SO", name: "The Southern Company", exchange: "NYSE" },
  { symbol: "DUK", name: "Duke Energy Corporation", exchange: "NYSE" },
  { symbol: "D", name: "Dominion Energy Inc.", exchange: "NYSE" },
  { symbol: "AEP", name: "American Electric Power", exchange: "NASDAQ" },
  { symbol: "SRE", name: "Sempra", exchange: "NYSE" },
  { symbol: "EXC", name: "Exelon Corporation", exchange: "NASDAQ" },
  { symbol: "XEL", name: "Xcel Energy Inc.", exchange: "NASDAQ" },
  { symbol: "ED", name: "Consolidated Edison Inc.", exchange: "NYSE" },
  { symbol: "PCG", name: "PG&E Corporation", exchange: "NYSE" },
  { symbol: "EIX", name: "Edison International", exchange: "NYSE" },
  { symbol: "WEC", name: "WEC Energy Group Inc.", exchange: "NYSE" },
  { symbol: "ES", name: "Eversource Energy", exchange: "NYSE" },
  { symbol: "AEE", name: "Ameren Corporation", exchange: "NYSE" },
  { symbol: "CMS", name: "CMS Energy Corporation", exchange: "NYSE" },
  { symbol: "DTE", name: "DTE Energy Company", exchange: "NYSE" },
  { symbol: "FE", name: "FirstEnergy Corp.", exchange: "NYSE" },
  { symbol: "PPL", name: "PPL Corporation", exchange: "NYSE" },
  { symbol: "ETR", name: "Entergy Corporation", exchange: "NYSE" },
  { symbol: "ATO", name: "Atmos Energy Corporation", exchange: "NYSE" },
  { symbol: "NI", name: "NiSource Inc.", exchange: "NYSE" },
  { symbol: "CNP", name: "CenterPoint Energy Inc.", exchange: "NYSE" },
  { symbol: "AWK", name: "American Water Works Company", exchange: "NYSE" },
  { symbol: "WTRG", name: "Essential Utilities Inc.", exchange: "NYSE" },
  { symbol: "VST", name: "Vistra Corp.", exchange: "NYSE" },
  { symbol: "CEG", name: "Constellation Energy Corporation", exchange: "NASDAQ" },

  // ═══════════════════════════════════════════
  // MATERIALS — Chemicals, Mining, Steel
  // ═══════════════════════════════════════════
  { symbol: "LIN", name: "Linde plc", exchange: "NASDAQ" },
  { symbol: "APD", name: "Air Products and Chemicals", exchange: "NYSE" },
  { symbol: "SHW", name: "The Sherwin-Williams Company", exchange: "NYSE" },
  { symbol: "FCX", name: "Freeport-McMoRan Inc.", exchange: "NYSE" },
  { symbol: "NEM", name: "Newmont Corporation", exchange: "NYSE" },
  { symbol: "NUE", name: "Nucor Corporation", exchange: "NYSE" },
  { symbol: "DOW", name: "Dow Inc.", exchange: "NYSE" },
  { symbol: "DD", name: "DuPont de Nemours Inc.", exchange: "NYSE" },
  { symbol: "ECL", name: "Ecolab Inc.", exchange: "NYSE" },
  { symbol: "PPG", name: "PPG Industries Inc.", exchange: "NYSE" },
  { symbol: "VMC", name: "Vulcan Materials Company", exchange: "NYSE" },
  { symbol: "MLM", name: "Martin Marietta Materials", exchange: "NYSE" },
  { symbol: "STLD", name: "Steel Dynamics Inc.", exchange: "NASDAQ" },
  { symbol: "RS", name: "Reliance Inc.", exchange: "NYSE" },
  { symbol: "CLF", name: "Cleveland-Cliffs Inc.", exchange: "NYSE" },
  { symbol: "X", name: "United States Steel Corporation", exchange: "NYSE" },
  { symbol: "AA", name: "Alcoa Corporation", exchange: "NYSE" },
  { symbol: "GOLD", name: "Barrick Gold Corporation", exchange: "NYSE" },
  { symbol: "AEM", name: "Agnico Eagle Mines Limited", exchange: "NYSE" },
  { symbol: "KGC", name: "Kinross Gold Corporation", exchange: "NYSE" },
  { symbol: "FNV", name: "Franco-Nevada Corporation", exchange: "NYSE" },
  { symbol: "WPM", name: "Wheaton Precious Metals Corp.", exchange: "NYSE" },
  { symbol: "RGLD", name: "Royal Gold Inc.", exchange: "NASDAQ" },
  { symbol: "PAAS", name: "Pan American Silver Corp.", exchange: "NASDAQ" },
  { symbol: "AG", name: "First Majestic Silver Corp.", exchange: "NYSE" },
  { symbol: "HL", name: "Hecla Mining Company", exchange: "NYSE" },
  { symbol: "CDE", name: "Coeur Mining Inc.", exchange: "NYSE" },
  { symbol: "MP", name: "MP Materials Corp.", exchange: "NYSE" },
  { symbol: "ALB", name: "Albemarle Corporation", exchange: "NYSE" },
  { symbol: "LTHM", name: "Livent Corporation", exchange: "NYSE" },
  { symbol: "LAC", name: "Lithium Americas Corp.", exchange: "NYSE" },
  { symbol: "BHP", name: "BHP Group Limited", exchange: "NYSE" },
  { symbol: "RIO", name: "Rio Tinto Group", exchange: "NYSE" },
  { symbol: "VALE", name: "Vale S.A.", exchange: "NYSE" },
  { symbol: "SCCO", name: "Southern Copper Corporation", exchange: "NYSE" },
  { symbol: "TECK", name: "Teck Resources Limited", exchange: "NYSE" },
  { symbol: "IFF", name: "International Flavors & Fragrances", exchange: "NYSE" },
  { symbol: "CE", name: "Celanese Corporation", exchange: "NYSE" },
  { symbol: "EMN", name: "Eastman Chemical Company", exchange: "NYSE" },
  { symbol: "RPM", name: "RPM International Inc.", exchange: "NYSE" },
  { symbol: "AXTA", name: "Axalta Coating Systems Ltd.", exchange: "NYSE" },
  { symbol: "OLN", name: "Olin Corporation", exchange: "NYSE" },
  { symbol: "HUN", name: "Huntsman Corporation", exchange: "NYSE" },
  { symbol: "WLK", name: "Westlake Corporation", exchange: "NYSE" },
  { symbol: "LYB", name: "LyondellBasell Industries", exchange: "NYSE" },
  { symbol: "CF", name: "CF Industries Holdings Inc.", exchange: "NYSE" },
  { symbol: "MOS", name: "The Mosaic Company", exchange: "NYSE" },
  { symbol: "NTR", name: "Nutrien Ltd.", exchange: "NYSE" },
  { symbol: "FMC", name: "FMC Corporation", exchange: "NYSE" },
  { symbol: "CTVA", name: "Corteva Inc.", exchange: "NYSE" },
  { symbol: "PKG", name: "Packaging Corporation of America", exchange: "NYSE" },
  { symbol: "IP", name: "International Paper Company", exchange: "NYSE" },
  { symbol: "WRK", name: "WestRock Company", exchange: "NYSE" },
  { symbol: "SEE", name: "Sealed Air Corporation", exchange: "NYSE" },
  { symbol: "SON", name: "Sonoco Products Company", exchange: "NYSE" },
  { symbol: "AVY", name: "Avery Dennison Corporation", exchange: "NYSE" },
  { symbol: "BLL", name: "Ball Corporation", exchange: "NYSE" },
  { symbol: "CCK", name: "Crown Holdings Inc.", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // COMMUNICATION SERVICES
  // ═══════════════════════════════════════════
  { symbol: "T", name: "AT&T Inc.", exchange: "NYSE" },
  { symbol: "VZ", name: "Verizon Communications", exchange: "NYSE" },
  { symbol: "TMUS", name: "T-Mobile US Inc.", exchange: "NASDAQ" },
  { symbol: "CMCSA", name: "Comcast Corporation", exchange: "NASDAQ" },
  { symbol: "CHTR", name: "Charter Communications", exchange: "NASDAQ" },
  { symbol: "NTES", name: "NetEase Inc.", exchange: "NASDAQ" },
  { symbol: "EA", name: "Electronic Arts Inc.", exchange: "NASDAQ" },
  { symbol: "TTWO", name: "Take-Two Interactive", exchange: "NASDAQ" },
  { symbol: "WBD", name: "Warner Bros. Discovery", exchange: "NASDAQ" },
  { symbol: "PARA", name: "Paramount Global", exchange: "NASDAQ" },
  { symbol: "FOX", name: "Fox Corporation", exchange: "NASDAQ" },
  { symbol: "FOXA", name: "Fox Corporation (Class A)", exchange: "NASDAQ" },
  { symbol: "LYV", name: "Live Nation Entertainment", exchange: "NYSE" },
  { symbol: "MTCH", name: "Match Group Inc.", exchange: "NASDAQ" },
  { symbol: "BMBL", name: "Bumble Inc.", exchange: "NASDAQ" },
  { symbol: "RBLX", name: "Roblox Corporation", exchange: "NYSE" },
  { symbol: "U", name: "Unity Software Inc.", exchange: "NYSE" },
  { symbol: "DKNG", name: "DraftKings Inc.", exchange: "NASDAQ" },
  { symbol: "PENN", name: "PENN Entertainment Inc.", exchange: "NASDAQ" },
  { symbol: "CZR", name: "Caesars Entertainment Inc.", exchange: "NASDAQ" },
  { symbol: "MGM", name: "MGM Resorts International", exchange: "NYSE" },
  { symbol: "WYNN", name: "Wynn Resorts Limited", exchange: "NASDAQ" },
  { symbol: "LVS", name: "Las Vegas Sands Corp.", exchange: "NYSE" },
  { symbol: "NWSA", name: "News Corporation (Class A)", exchange: "NASDAQ" },
  { symbol: "IPG", name: "Interpublic Group of Companies", exchange: "NYSE" },
  { symbol: "OMC", name: "Omnicom Group Inc.", exchange: "NYSE" },
  { symbol: "ZD", name: "Ziff Davis Inc.", exchange: "NASDAQ" },
  { symbol: "IAC", name: "IAC Inc.", exchange: "NASDAQ" },
  { symbol: "YELP", name: "Yelp Inc.", exchange: "NYSE" },
  { symbol: "COUR", name: "Coursera Inc.", exchange: "NYSE" },
  { symbol: "DUOL", name: "Duolingo Inc.", exchange: "NASDAQ" },
  { symbol: "LBRDK", name: "Liberty Broadband Corporation", exchange: "NASDAQ" },
  { symbol: "FWONK", name: "Liberty Media Formula One", exchange: "NASDAQ" },
  { symbol: "SIRI", name: "Sirius XM Holdings Inc.", exchange: "NASDAQ" },

  // ═══════════════════════════════════════════
  // GAMING, ENTERTAINMENT, MEDIA
  // ═══════════════════════════════════════════
  { symbol: "NFLX", name: "Netflix Inc.", exchange: "NASDAQ" },
  { symbol: "DIS", name: "The Walt Disney Company", exchange: "NYSE" },
  { symbol: "AMCX", name: "AMC Networks Inc.", exchange: "NASDAQ" },
  { symbol: "AMC", name: "AMC Entertainment Holdings", exchange: "NYSE" },
  { symbol: "CNK", name: "Cinemark Holdings Inc.", exchange: "NYSE" },
  { symbol: "IMAX", name: "IMAX Corporation", exchange: "NYSE" },
  { symbol: "LGF.A", name: "Lionsgate Entertainment (Class A)", exchange: "NYSE" },
  { symbol: "MSGS", name: "Madison Square Garden Sports", exchange: "NYSE" },
  { symbol: "MSGE", name: "Madison Square Garden Entertainment", exchange: "NYSE" },
  { symbol: "EDR", name: "Endeavor Group Holdings", exchange: "NYSE" },
  { symbol: "WWE", name: "World Wrestling Entertainment", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // AI, QUANTUM, ROBOTICS — Hot / Trending
  // ═══════════════════════════════════════════
  { symbol: "AI", name: "C3.ai Inc.", exchange: "NYSE" },
  { symbol: "IONQ", name: "IonQ Inc.", exchange: "NYSE" },
  { symbol: "RGTI", name: "Rigetti Computing Inc.", exchange: "NASDAQ" },
  { symbol: "BBAI", name: "BigBear.ai Holdings Inc.", exchange: "NYSE" },
  { symbol: "SOUN", name: "SoundHound AI Inc.", exchange: "NASDAQ" },
  { symbol: "OPEN", name: "Opendoor Technologies", exchange: "NASDAQ" },
  { symbol: "CLOV", name: "Clover Health Investments", exchange: "NASDAQ" },
  { symbol: "QUBT", name: "Quantum Computing Inc.", exchange: "NASDAQ" },
  { symbol: "ARQQ", name: "Arqit Quantum Inc.", exchange: "NASDAQ" },
  { symbol: "QBTS", name: "D-Wave Quantum Inc.", exchange: "NYSE" },
  { symbol: "GFAI", name: "Guardforce AI Co. Limited", exchange: "NASDAQ" },
  { symbol: "PRCT", name: "PROCEPT BioRobotics Corp.", exchange: "NASDAQ" },
  { symbol: "IRBT", name: "iRobot Corporation", exchange: "NASDAQ" },
  { symbol: "ISRG", name: "Intuitive Surgical Inc.", exchange: "NASDAQ" },

  // ═══════════════════════════════════════════
  // CRYPTO-RELATED
  // ═══════════════════════════════════════════
  { symbol: "MSTR", name: "MicroStrategy Incorporated", exchange: "NASDAQ" },
  { symbol: "MARA", name: "Marathon Digital Holdings", exchange: "NASDAQ" },
  { symbol: "RIOT", name: "Riot Platforms Inc.", exchange: "NASDAQ" },
  { symbol: "BITF", name: "Bitfarms Ltd.", exchange: "NASDAQ" },
  { symbol: "HUT", name: "Hut 8 Corp.", exchange: "NASDAQ" },
  { symbol: "CLSK", name: "CleanSpark Inc.", exchange: "NASDAQ" },
  { symbol: "CIFR", name: "Cipher Mining Inc.", exchange: "NASDAQ" },
  { symbol: "IREN", name: "Iris Energy Limited", exchange: "NASDAQ" },
  { symbol: "BTBT", name: "Bit Digital Inc.", exchange: "NASDAQ" },
  { symbol: "WULF", name: "TeraWulf Inc.", exchange: "NASDAQ" },
  { symbol: "CORZ", name: "Core Scientific Inc.", exchange: "NASDAQ" },
  { symbol: "BTDR", name: "Bitdeer Technologies Group", exchange: "NASDAQ" },

  // ═══════════════════════════════════════════
  // CANNABIS
  // ═══════════════════════════════════════════
  { symbol: "TLRY", name: "Tilray Brands Inc.", exchange: "NASDAQ" },
  { symbol: "CGC", name: "Canopy Growth Corporation", exchange: "NASDAQ" },
  { symbol: "ACB", name: "Aurora Cannabis Inc.", exchange: "NASDAQ" },
  { symbol: "SNDL", name: "SNDL Inc.", exchange: "NASDAQ" },
  { symbol: "OGI", name: "Organigram Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "CRON", name: "Cronos Group Inc.", exchange: "NASDAQ" },
  { symbol: "HEXO", name: "HEXO Corp.", exchange: "NASDAQ" },

  // ═══════════════════════════════════════════
  // SPACE & DEFENSE TECH
  // ═══════════════════════════════════════════
  { symbol: "RKLB", name: "Rocket Lab USA Inc.", exchange: "NASDAQ" },
  { symbol: "SPCE", name: "Virgin Galactic Holdings", exchange: "NYSE" },
  { symbol: "ASTS", name: "AST SpaceMobile Inc.", exchange: "NASDAQ" },
  { symbol: "LUNR", name: "Intuitive Machines Inc.", exchange: "NASDAQ" },
  { symbol: "RDW", name: "Redwire Corporation", exchange: "NYSE" },
  { symbol: "MNTS", name: "Momentus Inc.", exchange: "NASDAQ" },
  { symbol: "ASTR", name: "Astra Space Inc.", exchange: "NASDAQ" },
  { symbol: "KTOS", name: "Kratos Defense & Security", exchange: "NASDAQ" },
  { symbol: "AVAV", name: "AeroVironment Inc.", exchange: "NASDAQ" },
  { symbol: "BWXT", name: "BWX Technologies Inc.", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // CHINESE / ASIAN ADRs
  // ═══════════════════════════════════════════
  { symbol: "BABA", name: "Alibaba Group Holding", exchange: "NYSE" },
  { symbol: "JD", name: "JD.com Inc.", exchange: "NASDAQ" },
  { symbol: "PDD", name: "PDD Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "BIDU", name: "Baidu Inc.", exchange: "NASDAQ" },
  { symbol: "TCEHY", name: "Tencent Holdings Limited", exchange: "OTC" },
  { symbol: "SE", name: "Sea Limited", exchange: "NYSE" },
  { symbol: "GRAB", name: "Grab Holdings Limited", exchange: "NASDAQ" },
  { symbol: "MELI", name: "MercadoLibre Inc.", exchange: "NASDAQ" },
  { symbol: "TME", name: "Tencent Music Entertainment", exchange: "NYSE" },
  { symbol: "BILI", name: "Bilibili Inc.", exchange: "NASDAQ" },
  { symbol: "IQ", name: "iQIYI Inc.", exchange: "NASDAQ" },
  { symbol: "VIPS", name: "Vipshop Holdings Limited", exchange: "NYSE" },
  { symbol: "ZTO", name: "ZTO Express (Cayman) Inc.", exchange: "NYSE" },
  { symbol: "FUTU", name: "Futu Holdings Limited", exchange: "NASDAQ" },
  { symbol: "MNSO", name: "MINISO Group Holding Limited", exchange: "NYSE" },
  { symbol: "TAL", name: "TAL Education Group", exchange: "NYSE" },
  { symbol: "EDU", name: "New Oriental Education & Tech", exchange: "NYSE" },
  { symbol: "DIDI", name: "DiDi Global Inc.", exchange: "OTC" },
  { symbol: "YMM", name: "Full Truck Alliance Co. Ltd.", exchange: "NYSE" },
  { symbol: "XPEV", name: "XPeng Inc.", exchange: "NYSE" },
  { symbol: "LI", name: "Li Auto Inc.", exchange: "NASDAQ" },
  { symbol: "NIO", name: "NIO Inc.", exchange: "NYSE" },
  { symbol: "WB", name: "Weibo Corporation", exchange: "NASDAQ" },
  { symbol: "TIGR", name: "UP Fintech Holding Limited", exchange: "NASDAQ" },
  { symbol: "KC", name: "Kingsoft Cloud Holdings Limited", exchange: "NASDAQ" },
  { symbol: "LEGN", name: "Legend Biotech Corporation", exchange: "NASDAQ" },

  // ═══════════════════════════════════════════
  // CRYPTOCURRENCY (tradeable via crypto ETFs & trusts)
  // ═══════════════════════════════════════════
  { symbol: "BTC-USD", name: "Bitcoin USD", exchange: "CRYPTO" },
  { symbol: "ETH-USD", name: "Ethereum USD", exchange: "CRYPTO" },
  { symbol: "SOL-USD", name: "Solana USD", exchange: "CRYPTO" },
  { symbol: "BNB-USD", name: "BNB (Binance Coin) USD", exchange: "CRYPTO" },
  { symbol: "XRP-USD", name: "XRP (Ripple) USD", exchange: "CRYPTO" },
  { symbol: "ADA-USD", name: "Cardano USD", exchange: "CRYPTO" },
  { symbol: "DOGE-USD", name: "Dogecoin USD", exchange: "CRYPTO" },
  { symbol: "SHIB-USD", name: "Shiba Inu USD", exchange: "CRYPTO" },
  { symbol: "DOT-USD", name: "Polkadot USD", exchange: "CRYPTO" },
  { symbol: "AVAX-USD", name: "Avalanche USD", exchange: "CRYPTO" },
  { symbol: "MATIC-USD", name: "Polygon (MATIC) USD", exchange: "CRYPTO" },
  { symbol: "LINK-USD", name: "Chainlink USD", exchange: "CRYPTO" },
  { symbol: "UNI-USD", name: "Uniswap USD", exchange: "CRYPTO" },
  { symbol: "ATOM-USD", name: "Cosmos USD", exchange: "CRYPTO" },
  { symbol: "LTC-USD", name: "Litecoin USD", exchange: "CRYPTO" },
  { symbol: "BCH-USD", name: "Bitcoin Cash USD", exchange: "CRYPTO" },
  { symbol: "XLM-USD", name: "Stellar USD", exchange: "CRYPTO" },
  { symbol: "ALGO-USD", name: "Algorand USD", exchange: "CRYPTO" },
  { symbol: "FIL-USD", name: "Filecoin USD", exchange: "CRYPTO" },
  { symbol: "NEAR-USD", name: "NEAR Protocol USD", exchange: "CRYPTO" },
  { symbol: "APT-USD", name: "Aptos USD", exchange: "CRYPTO" },
  { symbol: "SUI-USD", name: "Sui USD", exchange: "CRYPTO" },
  { symbol: "ARB-USD", name: "Arbitrum USD", exchange: "CRYPTO" },
  { symbol: "OP-USD", name: "Optimism USD", exchange: "CRYPTO" },
  { symbol: "PEPE-USD", name: "Pepe USD", exchange: "CRYPTO" },
  { symbol: "BONK-USD", name: "Bonk USD", exchange: "CRYPTO" },
  { symbol: "WIF-USD", name: "dogwifhat USD", exchange: "CRYPTO" },
  { symbol: "RENDER-USD", name: "Render Token USD", exchange: "CRYPTO" },
  { symbol: "INJ-USD", name: "Injective USD", exchange: "CRYPTO" },
  { symbol: "AAVE-USD", name: "Aave USD", exchange: "CRYPTO" },
  { symbol: "MKR-USD", name: "Maker USD", exchange: "CRYPTO" },
  { symbol: "CRV-USD", name: "Curve DAO Token USD", exchange: "CRYPTO" },
  { symbol: "SAND-USD", name: "The Sandbox USD", exchange: "CRYPTO" },
  { symbol: "MANA-USD", name: "Decentraland USD", exchange: "CRYPTO" },
  { symbol: "AXS-USD", name: "Axie Infinity USD", exchange: "CRYPTO" },
  { symbol: "GRT-USD", name: "The Graph USD", exchange: "CRYPTO" },
  { symbol: "FET-USD", name: "Fetch.ai USD", exchange: "CRYPTO" },
  { symbol: "RNDR-USD", name: "Render USD", exchange: "CRYPTO" },
  { symbol: "TIA-USD", name: "Celestia USD", exchange: "CRYPTO" },
  { symbol: "SEI-USD", name: "Sei USD", exchange: "CRYPTO" },
  { symbol: "HBAR-USD", name: "Hedera USD", exchange: "CRYPTO" },
  { symbol: "VET-USD", name: "VeChain USD", exchange: "CRYPTO" },
  { symbol: "ICP-USD", name: "Internet Computer USD", exchange: "CRYPTO" },
  { symbol: "IMX-USD", name: "Immutable X USD", exchange: "CRYPTO" },
  { symbol: "RUNE-USD", name: "THORChain USD", exchange: "CRYPTO" },
  { symbol: "STX-USD", name: "Stacks USD", exchange: "CRYPTO" },
  { symbol: "JASMY-USD", name: "JasmyCoin USD", exchange: "CRYPTO" },
  { symbol: "ENS-USD", name: "Ethereum Name Service USD", exchange: "CRYPTO" },

  // ═══════════════════════════════════════════
  // INDIAN ADRs (expanded — major Indian companies)
  // ═══════════════════════════════════════════
  { symbol: "INFY", name: "Infosys Limited", exchange: "NYSE" },
  { symbol: "WIT", name: "Wipro Limited", exchange: "NYSE" },
  { symbol: "HDB", name: "HDFC Bank Limited", exchange: "NYSE" },
  { symbol: "IBN", name: "ICICI Bank Limited", exchange: "NYSE" },
  { symbol: "SIFY", name: "Sify Technologies Limited", exchange: "NASDAQ" },
  { symbol: "RDY", name: "Dr. Reddy's Laboratories", exchange: "NYSE" },
  { symbol: "TTM", name: "Tata Motors Limited", exchange: "NYSE" },
  { symbol: "WNS", name: "WNS Holdings Limited", exchange: "NYSE" },
  { symbol: "MMYT", name: "MakeMyTrip Limited", exchange: "NASDAQ" },
  { symbol: "VTRS", name: "Viatris Inc.", exchange: "NASDAQ" },
  { symbol: "SIRI", name: "Sirius XM Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "YTRA", name: "Yatra Online Inc.", exchange: "NASDAQ" },
  { symbol: "AZRE", name: "Azure Power Global Limited", exchange: "NYSE" },
  { symbol: "MAPS", name: "WM Technology Inc.", exchange: "NASDAQ" },
  { symbol: "CX", name: "CEMEX S.A.B. de C.V.", exchange: "NYSE" },
  { symbol: "LPL", name: "LG Display Co.", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // JAPANESE ADRs (expanded — major Japanese companies)
  // ═══════════════════════════════════════════
  { symbol: "SONY", name: "Sony Group Corporation", exchange: "NYSE" },
  { symbol: "TM", name: "Toyota Motor Corporation", exchange: "NYSE" },
  { symbol: "HMC", name: "Honda Motor Co. Ltd.", exchange: "NYSE" },
  { symbol: "MUFG", name: "Mitsubishi UFJ Financial Group", exchange: "NYSE" },
  { symbol: "NMR", name: "Nomura Holdings Inc.", exchange: "NYSE" },
  { symbol: "SMFG", name: "Sumitomo Mitsui Financial", exchange: "NYSE" },
  { symbol: "MFG", name: "Mizuho Financial Group Inc.", exchange: "NYSE" },
  { symbol: "IX", name: "ORIX Corporation", exchange: "NYSE" },
  { symbol: "CAJ", name: "Canon Inc.", exchange: "NYSE" },
  { symbol: "NTDOY", name: "Nintendo Co. Ltd.", exchange: "OTC" },
  { symbol: "NSRGY", name: "Nestlé S.A.", exchange: "OTC" },
  { symbol: "KYOCY", name: "Kyocera Corporation", exchange: "OTC" },
  { symbol: "FUJIY", name: "FUJIFILM Holdings Corp.", exchange: "OTC" },
  { symbol: "DSCSY", name: "Disco Corporation", exchange: "OTC" },
  { symbol: "TOELY", name: "Tokyo Electron Limited", exchange: "OTC" },
  { symbol: "SFTBY", name: "SoftBank Group Corp.", exchange: "OTC" },
  { symbol: "RCRUY", name: "Recruit Holdings Co. Ltd.", exchange: "OTC" },
  { symbol: "HNDAF", name: "Honda Motor Co. Ltd.", exchange: "OTC" },
  { symbol: "FANUY", name: "Fanuc Corporation", exchange: "OTC" },
  { symbol: "MRAAY", name: "Murata Manufacturing Co.", exchange: "OTC" },
  { symbol: "DNZOY", name: "Denso Corporation", exchange: "OTC" },
  { symbol: "KNBWY", name: "Kobe Steel Ltd.", exchange: "OTC" },
  { symbol: "TKOMY", name: "Tokio Marine Holdings Inc.", exchange: "OTC" },
  { symbol: "AJINY", name: "Ajinomoto Co. Inc.", exchange: "OTC" },
  { symbol: "ALPMY", name: "Alps Alpine Co. Ltd.", exchange: "OTC" },

  // ═══════════════════════════════════════════
  // TRAVEL & LEISURE (expanded)
  // ═══════════════════════════════════════════
  { symbol: "BKNG", name: "Booking Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "ABNB", name: "Airbnb Inc.", exchange: "NASDAQ" },
  { symbol: "EXPE", name: "Expedia Group Inc.", exchange: "NASDAQ" },
  { symbol: "TRIP", name: "Tripadvisor Inc.", exchange: "NASDAQ" },
  { symbol: "MMYT", name: "MakeMyTrip Limited", exchange: "NASDAQ" },
  { symbol: "DESP", name: "Despegar.com Corp.", exchange: "NYSE" },
  { symbol: "TCOM", name: "Trip.com Group Limited", exchange: "NASDAQ" },
  { symbol: "SABR", name: "Sabre Corporation", exchange: "NASDAQ" },
  { symbol: "TVPT", name: "Travelport Worldwide Limited", exchange: "NYSE" },
  { symbol: "PLYA", name: "Playa Hotels & Resorts N.V.", exchange: "NASDAQ" },
  { symbol: "TNL", name: "Travel + Leisure Co.", exchange: "NYSE" },
  { symbol: "VAC", name: "Marriott Vacations Worldwide", exchange: "NYSE" },
  { symbol: "HGV", name: "Hilton Grand Vacations Inc.", exchange: "NYSE" },
  { symbol: "IHG", name: "InterContinental Hotels Group", exchange: "NYSE" },
  { symbol: "HTHT", name: "H World Group Limited", exchange: "NASDAQ" },
  { symbol: "SIX", name: "Six Flags Entertainment Corp.", exchange: "NYSE" },
  { symbol: "FUN", name: "Cedar Fair L.P.", exchange: "NYSE" },
  { symbol: "SEAS", name: "SeaWorld Entertainment Inc.", exchange: "NYSE" },
  { symbol: "MTN", name: "Vail Resorts Inc.", exchange: "NYSE" },
  { symbol: "SKI", name: "Peak Resorts Inc.", exchange: "NASDAQ" },

  // ═══════════════════════════════════════════
  // KOREAN ADRs
  // ═══════════════════════════════════════════
  { symbol: "SSNLF", name: "Samsung Electronics Co.", exchange: "OTC" },
  { symbol: "LPL", name: "LG Display Co.", exchange: "NYSE" },
  { symbol: "KB", name: "KB Financial Group Inc.", exchange: "NYSE" },
  { symbol: "SHG", name: "Shinhan Financial Group", exchange: "NYSE" },
  { symbol: "PKX", name: "POSCO Holdings Inc.", exchange: "NYSE" },
  { symbol: "SKM", name: "SK Telecom Co. Ltd.", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // EUROPEAN ADRs
  // ═══════════════════════════════════════════
  { symbol: "UL", name: "Unilever PLC", exchange: "NYSE" },
  { symbol: "DEO", name: "Diageo plc", exchange: "NYSE" },
  { symbol: "SAN", name: "Banco Santander S.A.", exchange: "NYSE" },
  { symbol: "HSBC", name: "HSBC Holdings plc", exchange: "NYSE" },
  { symbol: "BCS", name: "Barclays PLC", exchange: "NYSE" },
  { symbol: "DB", name: "Deutsche Bank AG", exchange: "NYSE" },
  { symbol: "LYG", name: "Lloyds Banking Group plc", exchange: "NYSE" },
  { symbol: "ING", name: "ING Groep N.V.", exchange: "NYSE" },
  { symbol: "CS", name: "Credit Suisse Group AG", exchange: "NYSE" },
  { symbol: "UBS", name: "UBS Group AG", exchange: "NYSE" },
  { symbol: "AZN", name: "AstraZeneca PLC", exchange: "NASDAQ" },
  { symbol: "NVS", name: "Novartis AG", exchange: "NYSE" },
  { symbol: "GSK", name: "GSK plc", exchange: "NYSE" },
  { symbol: "SNY", name: "Sanofi", exchange: "NASDAQ" },
  { symbol: "RACE", name: "Ferrari N.V.", exchange: "NYSE" },
  { symbol: "SPOT", name: "Spotify Technology S.A.", exchange: "NYSE" },
  { symbol: "NVO", name: "Novo Nordisk A/S", exchange: "NYSE" },
  { symbol: "SHOP", name: "Shopify Inc.", exchange: "NYSE" },
  { symbol: "TD", name: "The Toronto-Dominion Bank", exchange: "NYSE" },
  { symbol: "RY", name: "Royal Bank of Canada", exchange: "NYSE" },
  { symbol: "BNS", name: "Bank of Nova Scotia", exchange: "NYSE" },
  { symbol: "BMO", name: "Bank of Montreal", exchange: "NYSE" },
  { symbol: "CM", name: "Canadian Imperial Bank of Commerce", exchange: "NYSE" },
  { symbol: "CNI", name: "Canadian National Railway Co.", exchange: "NYSE" },
  { symbol: "CP", name: "Canadian Pacific Kansas City", exchange: "NYSE" },
  { symbol: "ENB", name: "Enbridge Inc.", exchange: "NYSE" },
  { symbol: "TRP", name: "TC Energy Corporation", exchange: "NYSE" },
  { symbol: "SU", name: "Suncor Energy Inc.", exchange: "NYSE" },
  { symbol: "CNQ", name: "Canadian Natural Resources", exchange: "NYSE" },
  { symbol: "GOLD", name: "Barrick Gold Corporation", exchange: "NYSE" },
  { symbol: "ABX", name: "Barrick Gold Corporation", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // LATIN AMERICA ADRs
  // ═══════════════════════════════════════════
  { symbol: "NU", name: "Nu Holdings Ltd.", exchange: "NYSE" },
  { symbol: "PBR", name: "Petróleo Brasileiro (Petrobras)", exchange: "NYSE" },
  { symbol: "ITUB", name: "Itaú Unibanco Holding S.A.", exchange: "NYSE" },
  { symbol: "SQM", name: "Sociedad Química y Minera", exchange: "NYSE" },
  { symbol: "BBVA", name: "Banco Bilbao Vizcaya Argentaria", exchange: "NYSE" },
  { symbol: "AMX", name: "América Móvil S.A.B. de C.V.", exchange: "NYSE" },
  { symbol: "FMX", name: "Fomento Económico Mexicano", exchange: "NYSE" },
  { symbol: "KOF", name: "Coca-Cola FEMSA S.A.B.", exchange: "NYSE" },
  { symbol: "BSBR", name: "Banco Santander (Brasil) S.A.", exchange: "NYSE" },
  { symbol: "BBD", name: "Banco Bradesco S.A.", exchange: "NYSE" },
  { symbol: "ABEV", name: "Ambev S.A.", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // MID & SMALL CAP — Popular names on Robinhood
  // ═══════════════════════════════════════════
  // Retail / E-commerce
  { symbol: "WISH", name: "ContextLogic Inc.", exchange: "NYSE" },
  { symbol: "REAL", name: "The RealReal Inc.", exchange: "NASDAQ" },
  { symbol: "POSH", name: "Poshmark Inc.", exchange: "NASDAQ" },
  { symbol: "FTCH", name: "Farfetch Limited", exchange: "NYSE" },
  { symbol: "OSTK", name: "Overstock.com Inc.", exchange: "NASDAQ" },
  { symbol: "BIG", name: "Big Lots Inc.", exchange: "NYSE" },
  { symbol: "PRTY", name: "Party City Holdco Inc.", exchange: "NYSE" },
  { symbol: "BBBY", name: "Bed Bath & Beyond Inc.", exchange: "NASDAQ" },
  { symbol: "EXPR", name: "Express Inc.", exchange: "NYSE" },
  { symbol: "ZUMZ", name: "Zumiez Inc.", exchange: "NASDAQ" },
  { symbol: "CATO", name: "The Cato Corporation", exchange: "NYSE" },
  { symbol: "PLCE", name: "The Children's Place Inc.", exchange: "NASDAQ" },
  { symbol: "SCVL", name: "Shoe Carnival Inc.", exchange: "NASDAQ" },

  // Food & Beverage Small/Mid
  { symbol: "BROS", name: "Dutch Bros Inc.", exchange: "NYSE" },
  { symbol: "SBUX", name: "Starbucks Corporation", exchange: "NASDAQ" },
  { symbol: "PLAY", name: "Dave & Buster's Entertainment", exchange: "NASDAQ" },
  { symbol: "LOCO", name: "El Pollo Loco Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "ARCO", name: "Arcos Dorados Holdings Inc.", exchange: "NYSE" },
  { symbol: "NDLS", name: "Noodles & Company", exchange: "NASDAQ" },
  { symbol: "FRSH", name: "Freshworks Inc.", exchange: "NASDAQ" },
  { symbol: "TAST", name: "Carrols Restaurant Group Inc.", exchange: "NASDAQ" },
  { symbol: "BJ", name: "BJ's Restaurants Inc.", exchange: "NASDAQ" },
  { symbol: "RUTH", name: "Ruth's Hospitality Group Inc.", exchange: "NASDAQ" },
  { symbol: "BJRI", name: "BJ's Restaurants Inc.", exchange: "NASDAQ" },
  { symbol: "DNUT", name: "Krispy Kreme Inc.", exchange: "NASDAQ" },
  { symbol: "WW", name: "WW International Inc.", exchange: "NASDAQ" },
  { symbol: "SMPL", name: "The Simply Good Foods Co.", exchange: "NASDAQ" },

  // Biotech Small Cap
  { symbol: "NVAX", name: "Novavax Inc.", exchange: "NASDAQ" },
  { symbol: "SAVA", name: "Cassava Sciences Inc.", exchange: "NASDAQ" },
  { symbol: "AGEN", name: "Agenus Inc.", exchange: "NASDAQ" },
  { symbol: "APLS", name: "Apellis Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "ARDX", name: "Ardelyx Inc.", exchange: "NASDAQ" },
  { symbol: "FOLD", name: "Amicus Therapeutics Inc.", exchange: "NASDAQ" },
  { symbol: "ARWR", name: "Arrowhead Pharmaceuticals", exchange: "NASDAQ" },
  { symbol: "ACAD", name: "ACADIA Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "DNLI", name: "Denali Therapeutics Inc.", exchange: "NASDAQ" },
  { symbol: "IONS", name: "Ionis Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "HALO", name: "Halozyme Therapeutics Inc.", exchange: "NASDAQ" },
  { symbol: "XENE", name: "Xenon Pharmaceuticals Inc.", exchange: "NASDAQ" },
  { symbol: "RXRX", name: "Recursion Pharmaceuticals", exchange: "NASDAQ" },

  // Fintech / Payment Small
  { symbol: "LMND", name: "Lemonade Inc.", exchange: "NYSE" },
  { symbol: "ROOT", name: "Root Inc.", exchange: "NASDAQ" },
  { symbol: "RELY", name: "Remitly Global Inc.", exchange: "NASDAQ" },
  { symbol: "PAYO", name: "Payoneer Global Inc.", exchange: "NASDAQ" },
  { symbol: "FLYW", name: "Flywire Corporation", exchange: "NASDAQ" },
  { symbol: "PSFE", name: "Paysafe Limited", exchange: "NYSE" },
  { symbol: "MQ", name: "Marqeta Inc.", exchange: "NASDAQ" },
  { symbol: "OLO", name: "Olo Inc.", exchange: "NYSE" },
  { symbol: "TOST", name: "Toast Inc.", exchange: "NYSE" },
  { symbol: "NUVEI", name: "Nuvei Corporation", exchange: "NASDAQ" },

  // Clean Energy / Solar / EV Charging
  { symbol: "PLUG", name: "Plug Power Inc.", exchange: "NASDAQ" },
  { symbol: "FCEL", name: "FuelCell Energy Inc.", exchange: "NASDAQ" },
  { symbol: "BLDP", name: "Ballard Power Systems Inc.", exchange: "NASDAQ" },
  { symbol: "BE", name: "Bloom Energy Corporation", exchange: "NYSE" },
  { symbol: "RUN", name: "Sunrun Inc.", exchange: "NASDAQ" },
  { symbol: "NOVA", name: "Sunnova Energy International", exchange: "NYSE" },
  { symbol: "SPWR", name: "SunPower Corporation", exchange: "NASDAQ" },
  { symbol: "JKS", name: "JinkoSolar Holding Co. Ltd.", exchange: "NYSE" },
  { symbol: "CSIQ", name: "Canadian Solar Inc.", exchange: "NASDAQ" },
  { symbol: "DQ", name: "Daqo New Energy Corp.", exchange: "NYSE" },
  { symbol: "ARRY", name: "Array Technologies Inc.", exchange: "NASDAQ" },
  { symbol: "CHPT", name: "ChargePoint Holdings Inc.", exchange: "NYSE" },
  { symbol: "EVGO", name: "EVgo Inc.", exchange: "NASDAQ" },
  { symbol: "BLNK", name: "Blink Charging Co.", exchange: "NASDAQ" },

  // Homebuilders
  { symbol: "DHI", name: "D.R. Horton Inc.", exchange: "NYSE" },
  { symbol: "LEN", name: "Lennar Corporation", exchange: "NYSE" },
  { symbol: "PHM", name: "PulteGroup Inc.", exchange: "NYSE" },
  { symbol: "NVR", name: "NVR Inc.", exchange: "NYSE" },
  { symbol: "TOL", name: "Toll Brothers Inc.", exchange: "NYSE" },
  { symbol: "KBH", name: "KB Home", exchange: "NYSE" },
  { symbol: "MDC", name: "M.D.C. Holdings Inc.", exchange: "NYSE" },
  { symbol: "MHO", name: "M/I Homes Inc.", exchange: "NYSE" },
  { symbol: "MTH", name: "Meritage Homes Corporation", exchange: "NYSE" },
  { symbol: "TMHC", name: "Taylor Morrison Home Corp.", exchange: "NYSE" },
  { symbol: "CCS", name: "Century Communities Inc.", exchange: "NYSE" },
  { symbol: "GRBK", name: "Green Brick Partners Inc.", exchange: "NYSE" },
  { symbol: "DFH", name: "Dream Finders Homes Inc.", exchange: "NASDAQ" },

  // Staffing / HR
  { symbol: "RHI", name: "Robert Half Inc.", exchange: "NYSE" },
  { symbol: "MAN", name: "ManpowerGroup Inc.", exchange: "NYSE" },
  { symbol: "HSON", name: "Hudson Global Inc.", exchange: "NASDAQ" },
  { symbol: "KFRC", name: "Kforce Inc.", exchange: "NASDAQ" },
  { symbol: "ASGN", name: "ASGN Incorporated", exchange: "NYSE" },
  { symbol: "NSIT", name: "Insight Enterprises Inc.", exchange: "NASDAQ" },

  // Services / Misc Small-Mid
  { symbol: "CVNA", name: "Carvana Co.", exchange: "NYSE" },
  { symbol: "OPAD", name: "Offerpad Solutions Inc.", exchange: "NYSE" },
  { symbol: "RDFN", name: "Redfin Corporation", exchange: "NASDAQ" },
  { symbol: "ZG", name: "Zillow Group Inc.", exchange: "NASDAQ" },
  { symbol: "Z", name: "Zillow Group Inc. (Class C)", exchange: "NASDAQ" },
  { symbol: "TREE", name: "LendingTree Inc.", exchange: "NASDAQ" },
  { symbol: "CSGP", name: "CoStar Group Inc.", exchange: "NASDAQ" },
  { symbol: "RKT", name: "Rocket Companies Inc.", exchange: "NYSE" },
  { symbol: "UWMC", name: "UWM Holdings Corporation", exchange: "NYSE" },
  { symbol: "PFSI", name: "PennyMac Financial Services", exchange: "NYSE" },
  { symbol: "SNEX", name: "StoneX Group Inc.", exchange: "NASDAQ" },
  { symbol: "WU", name: "The Western Union Company", exchange: "NYSE" },
  { symbol: "EEFT", name: "Euronet Worldwide Inc.", exchange: "NASDAQ" },
  { symbol: "GPN", name: "Global Payments Inc.", exchange: "NYSE" },
  { symbol: "JKHY", name: "Jack Henry & Associates Inc.", exchange: "NASDAQ" },
  { symbol: "WEX", name: "WEX Inc.", exchange: "NYSE" },
  { symbol: "FLT", name: "FLEETCOR Technologies Inc.", exchange: "NYSE" },

  // 3D Printing
  { symbol: "DDD", name: "3D Systems Corporation", exchange: "NYSE" },
  { symbol: "SSYS", name: "Stratasys Ltd.", exchange: "NASDAQ" },
  { symbol: "DM", name: "Desktop Metal Inc.", exchange: "NYSE" },
  { symbol: "XONE", name: "ExOne Company", exchange: "NASDAQ" },
  { symbol: "NNDM", name: "Nano Dimension Ltd.", exchange: "NASDAQ" },
  { symbol: "MKFG", name: "Markforged Holding Corp.", exchange: "NYSE" },

  // Cybersecurity Small
  { symbol: "CRWD", name: "CrowdStrike Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "CYBR", name: "CyberArk Software Ltd.", exchange: "NASDAQ" },
  { symbol: "SAIL", name: "SailPoint Technologies Holdings", exchange: "NASDAQ" },
  { symbol: "VRNT", name: "Verint Systems Inc.", exchange: "NASDAQ" },
  { symbol: "CYBE", name: "CyberOptics Corporation", exchange: "NASDAQ" },

  // Misc mid/small popular
  { symbol: "MNDY", name: "monday.com Ltd.", exchange: "NASDAQ" },
  { symbol: "FVRR", name: "Fiverr International Ltd.", exchange: "NYSE" },
  { symbol: "UPWK", name: "Upwork Inc.", exchange: "NASDAQ" },
  { symbol: "TASK", name: "TaskUs Inc.", exchange: "NASDAQ" },
  { symbol: "ASAN", name: "Asana Inc.", exchange: "NYSE" },
  { symbol: "ZI", name: "ZoomInfo Technologies Inc.", exchange: "NASDAQ" },
  { symbol: "SEMR", name: "SEMrush Holdings Inc.", exchange: "NYSE" },
  { symbol: "DOCS", name: "Doximity Inc.", exchange: "NYSE" },
  { symbol: "GRND", name: "Grindr Inc.", exchange: "NYSE" },
  { symbol: "KIND", name: "Nextdoor Holdings Inc.", exchange: "NYSE" },
  { symbol: "EDIT", name: "Editas Medicine Inc.", exchange: "NASDAQ" },
  { symbol: "CRSP", name: "CRISPR Therapeutics AG", exchange: "NASDAQ" },
  { symbol: "NTLA", name: "Intellia Therapeutics Inc.", exchange: "NASDAQ" },
  { symbol: "BEAM", name: "Beam Therapeutics Inc.", exchange: "NASDAQ" },
  { symbol: "VERV", name: "Verve Therapeutics Inc.", exchange: "NASDAQ" },
  { symbol: "PRME", name: "Prime Medicine Inc.", exchange: "NASDAQ" },
  { symbol: "DNA", name: "Ginkgo Bioworks Holdings Inc.", exchange: "NYSE" },
  { symbol: "SANA", name: "Sana Biotechnology Inc.", exchange: "NASDAQ" },
  { symbol: "VIR", name: "Vir Biotechnology Inc.", exchange: "NASDAQ" },
  { symbol: "RLAY", name: "Relay Therapeutics Inc.", exchange: "NASDAQ" },

  // SPACs / De-SPACs popular
  { symbol: "DKNG", name: "DraftKings Inc.", exchange: "NASDAQ" },
  { symbol: "JOBY", name: "Joby Aviation Inc.", exchange: "NYSE" },
  { symbol: "LILM", name: "Lilium N.V.", exchange: "NASDAQ" },
  { symbol: "ACHR", name: "Archer Aviation Inc.", exchange: "NYSE" },

  // Telehealth / Digital Health
  { symbol: "TDOC", name: "Teladoc Health Inc.", exchange: "NYSE" },
  { symbol: "AMWL", name: "American Well Corporation", exchange: "NYSE" },
  { symbol: "GDRX", name: "GoodRx Holdings Inc.", exchange: "NASDAQ" },
  { symbol: "HIMS", name: "Hims & Hers Health Inc.", exchange: "NYSE" },
  { symbol: "OSCR", name: "Oscar Health Inc.", exchange: "NYSE" },

  // Shipping / Logistics
  { symbol: "ZIM", name: "ZIM Integrated Shipping Services", exchange: "NYSE" },
  { symbol: "DAC", name: "Danaos Corporation", exchange: "NYSE" },
  { symbol: "GOGL", name: "Golden Ocean Group Limited", exchange: "NASDAQ" },
  { symbol: "EGLE", name: "Eagle Bulk Shipping Inc.", exchange: "NYSE" },
  { symbol: "SBLK", name: "Star Bulk Carriers Corp.", exchange: "NASDAQ" },
  { symbol: "INSW", name: "International Seaways Inc.", exchange: "NYSE" },

  // ═══════════════════════════════════════════
  // POPULAR ETFs — Broad, Sector, Thematic
  // ═══════════════════════════════════════════
  { symbol: "SPY", name: "SPDR S&P 500 ETF Trust", exchange: "NYSE" },
  { symbol: "QQQ", name: "Invesco QQQ Trust", exchange: "NASDAQ" },
  { symbol: "IWM", name: "iShares Russell 2000 ETF", exchange: "NYSE" },
  { symbol: "DIA", name: "SPDR Dow Jones Industrial ETF", exchange: "NYSE" },
  { symbol: "VTI", name: "Vanguard Total Stock Market ETF", exchange: "NYSE" },
  { symbol: "VOO", name: "Vanguard S&P 500 ETF", exchange: "NYSE" },
  { symbol: "VGT", name: "Vanguard Information Technology ETF", exchange: "NYSE" },
  { symbol: "ARKK", name: "ARK Innovation ETF", exchange: "NYSE" },
  { symbol: "ARKW", name: "ARK Next Generation Internet ETF", exchange: "NYSE" },
  { symbol: "ARKF", name: "ARK Fintech Innovation ETF", exchange: "NYSE" },
  { symbol: "ARKG", name: "ARK Genomic Revolution ETF", exchange: "NYSE" },
  { symbol: "ARKQ", name: "ARK Autonomous Technology ETF", exchange: "NYSE" },
  { symbol: "XLF", name: "Financial Select Sector SPDR", exchange: "NYSE" },
  { symbol: "XLE", name: "Energy Select Sector SPDR", exchange: "NYSE" },
  { symbol: "XLK", name: "Technology Select Sector SPDR", exchange: "NYSE" },
  { symbol: "XLV", name: "Health Care Select Sector SPDR", exchange: "NYSE" },
  { symbol: "XLI", name: "Industrial Select Sector SPDR", exchange: "NYSE" },
  { symbol: "XLY", name: "Consumer Discretionary Select Sector SPDR", exchange: "NYSE" },
  { symbol: "XLP", name: "Consumer Staples Select Sector SPDR", exchange: "NYSE" },
  { symbol: "XLU", name: "Utilities Select Sector SPDR", exchange: "NYSE" },
  { symbol: "XLB", name: "Materials Select Sector SPDR", exchange: "NYSE" },
  { symbol: "XLRE", name: "Real Estate Select Sector SPDR", exchange: "NYSE" },
  { symbol: "XLC", name: "Communication Services Select Sector SPDR", exchange: "NYSE" },
  { symbol: "GLD", name: "SPDR Gold Shares", exchange: "NYSE" },
  { symbol: "SLV", name: "iShares Silver Trust", exchange: "NYSE" },
  { symbol: "TLT", name: "iShares 20+ Year Treasury Bond", exchange: "NASDAQ" },
  { symbol: "HYG", name: "iShares iBoxx $ High Yield Corporate Bond", exchange: "NYSE" },
  { symbol: "LQD", name: "iShares iBoxx $ Investment Grade Corporate Bond", exchange: "NYSE" },
  { symbol: "AGG", name: "iShares Core U.S. Aggregate Bond", exchange: "NYSE" },
  { symbol: "BND", name: "Vanguard Total Bond Market ETF", exchange: "NASDAQ" },
  { symbol: "BNDX", name: "Vanguard Total International Bond ETF", exchange: "NASDAQ" },
  { symbol: "TIP", name: "iShares TIPS Bond ETF", exchange: "NYSE" },
  { symbol: "SHY", name: "iShares 1-3 Year Treasury Bond ETF", exchange: "NASDAQ" },
  { symbol: "IEF", name: "iShares 7-10 Year Treasury Bond", exchange: "NASDAQ" },
  { symbol: "VCSH", name: "Vanguard Short-Term Corporate Bond", exchange: "NASDAQ" },
  { symbol: "VCIT", name: "Vanguard Intermediate-Term Corporate Bond", exchange: "NASDAQ" },
  { symbol: "EMB", name: "iShares JP Morgan USD Emerging Markets Bond", exchange: "NASDAQ" },
  { symbol: "VNQ", name: "Vanguard Real Estate ETF", exchange: "NYSE" },
  { symbol: "SCHD", name: "Schwab U.S. Dividend Equity ETF", exchange: "NYSE" },
  { symbol: "VYM", name: "Vanguard High Dividend Yield ETF", exchange: "NYSE" },
  { symbol: "DVY", name: "iShares Select Dividend ETF", exchange: "NASDAQ" },
  { symbol: "HDV", name: "iShares Core High Dividend ETF", exchange: "NYSE" },
  { symbol: "DGRO", name: "iShares Core Dividend Growth ETF", exchange: "NYSE" },
  { symbol: "NOBL", name: "ProShares S&P 500 Dividend Aristocrats", exchange: "NYSE" },
  { symbol: "VIG", name: "Vanguard Dividend Appreciation ETF", exchange: "NYSE" },
  { symbol: "JEPI", name: "JPMorgan Equity Premium Income ETF", exchange: "NYSE" },
  { symbol: "JEPQ", name: "JPMorgan Nasdaq Equity Premium Income ETF", exchange: "NASDAQ" },
  { symbol: "QYLD", name: "Global X NASDAQ 100 Covered Call ETF", exchange: "NASDAQ" },
  { symbol: "XYLD", name: "Global X S&P 500 Covered Call ETF", exchange: "NYSE" },
  { symbol: "TQQQ", name: "ProShares UltraPro QQQ", exchange: "NASDAQ" },
  { symbol: "SQQQ", name: "ProShares UltraPro Short QQQ", exchange: "NASDAQ" },
  { symbol: "SPXL", name: "Direxion Daily S&P 500 Bull 3X", exchange: "NYSE" },
  { symbol: "SPXS", name: "Direxion Daily S&P 500 Bear 3X", exchange: "NYSE" },
  { symbol: "SOXL", name: "Direxion Daily Semiconductor Bull 3X", exchange: "NYSE" },
  { symbol: "SOXS", name: "Direxion Daily Semiconductor Bear 3X", exchange: "NYSE" },
  { symbol: "LABU", name: "Direxion Daily S&P Biotech Bull 3X", exchange: "NYSE" },
  { symbol: "UVXY", name: "ProShares Ultra VIX Short-Term Futures", exchange: "NYSE" },
  { symbol: "VXX", name: "iPath Series B S&P 500 VIX Short-Term", exchange: "NYSE" },
  { symbol: "USO", name: "United States Oil Fund", exchange: "NYSE" },
  { symbol: "UNG", name: "United States Natural Gas Fund", exchange: "NYSE" },
  { symbol: "BITO", name: "ProShares Bitcoin Strategy ETF", exchange: "NYSE" },
  { symbol: "IBIT", name: "iShares Bitcoin Trust ETF", exchange: "NASDAQ" },
  { symbol: "FBTC", name: "Fidelity Wise Origin Bitcoin Fund", exchange: "NYSE" },
  { symbol: "GBTC", name: "Grayscale Bitcoin Trust", exchange: "OTC" },
  { symbol: "ETHE", name: "Grayscale Ethereum Trust", exchange: "OTC" },
  { symbol: "BITQ", name: "Bitwise Crypto Industry Innovators ETF", exchange: "NYSE" },
  // International ETFs
  { symbol: "EEM", name: "iShares MSCI Emerging Markets ETF", exchange: "NYSE" },
  { symbol: "VWO", name: "Vanguard FTSE Emerging Markets ETF", exchange: "NYSE" },
  { symbol: "INDA", name: "iShares MSCI India ETF", exchange: "NYSE" },
  { symbol: "MCHI", name: "iShares MSCI China ETF", exchange: "NASDAQ" },
  { symbol: "EWJ", name: "iShares MSCI Japan ETF", exchange: "NYSE" },
  { symbol: "EWZ", name: "iShares MSCI Brazil ETF", exchange: "NYSE" },
  { symbol: "EWG", name: "iShares MSCI Germany ETF", exchange: "NYSE" },
  { symbol: "EWU", name: "iShares MSCI United Kingdom ETF", exchange: "NYSE" },
  { symbol: "FXI", name: "iShares China Large-Cap ETF", exchange: "NYSE" },
  { symbol: "KWEB", name: "KraneShares CSI China Internet ETF", exchange: "NYSE" },
  { symbol: "IEMG", name: "iShares Core MSCI Emerging Markets", exchange: "NYSE" },
  { symbol: "EFA", name: "iShares MSCI EAFE ETF", exchange: "NYSE" },
  { symbol: "VXUS", name: "Vanguard Total International Stock", exchange: "NASDAQ" },
  { symbol: "EPI", name: "WisdomTree India Earnings Fund", exchange: "NYSE" },
  { symbol: "PIN", name: "Invesco India ETF", exchange: "NYSE" },
  { symbol: "INDY", name: "iShares India 50 ETF (Nifty 50)", exchange: "NASDAQ" },
  { symbol: "EWT", name: "iShares MSCI Taiwan ETF", exchange: "NYSE" },
  { symbol: "EWY", name: "iShares MSCI South Korea ETF", exchange: "NYSE" },
  { symbol: "VEA", name: "Vanguard FTSE Developed Markets ETF", exchange: "NYSE" },
  { symbol: "IEFA", name: "iShares Core MSCI EAFE ETF", exchange: "NYSE" },
  { symbol: "EWC", name: "iShares MSCI Canada ETF", exchange: "NYSE" },
  { symbol: "EWA", name: "iShares MSCI Australia ETF", exchange: "NYSE" },
  { symbol: "EWH", name: "iShares MSCI Hong Kong ETF", exchange: "NYSE" },
  { symbol: "EWS", name: "iShares MSCI Singapore ETF", exchange: "NYSE" },
  { symbol: "THD", name: "iShares MSCI Thailand ETF", exchange: "NYSE" },
  { symbol: "EPHE", name: "iShares MSCI Philippines ETF", exchange: "NYSE" },
  { symbol: "VNM", name: "VanEck Vietnam ETF", exchange: "NYSE" },
  { symbol: "FM", name: "iShares MSCI Frontier and Select EM ETF", exchange: "NYSE" },
  // Thematic ETFs
  { symbol: "SOXX", name: "iShares Semiconductor ETF", exchange: "NASDAQ" },
  { symbol: "SMH", name: "VanEck Semiconductor ETF", exchange: "NASDAQ" },
  { symbol: "HACK", name: "ETFMG Prime Cyber Security ETF", exchange: "NYSE" },
  { symbol: "ROBO", name: "ROBO Global Robotics and Automation ETF", exchange: "NYSE" },
  { symbol: "BOTZ", name: "Global X Robotics & Artificial Intelligence ETF", exchange: "NASDAQ" },
  { symbol: "AIQ", name: "Global X Artificial Intelligence & Technology ETF", exchange: "NASDAQ" },
  { symbol: "SKYY", name: "First Trust Cloud Computing ETF", exchange: "NASDAQ" },
  { symbol: "WCLD", name: "WisdomTree Cloud Computing Fund", exchange: "NASDAQ" },
  { symbol: "FINX", name: "Global X FinTech ETF", exchange: "NASDAQ" },
  { symbol: "DRIV", name: "Global X Autonomous & Electric Vehicles ETF", exchange: "NASDAQ" },
  { symbol: "LIT", name: "Global X Lithium & Battery Tech ETF", exchange: "NYSE" },
  { symbol: "TAN", name: "Invesco Solar ETF", exchange: "NYSE" },
  { symbol: "ICLN", name: "iShares Global Clean Energy ETF", exchange: "NASDAQ" },
  { symbol: "QCLN", name: "First Trust NASDAQ Clean Edge Green Energy ETF", exchange: "NASDAQ" },
  { symbol: "PBW", name: "Invesco WilderHill Clean Energy ETF", exchange: "NYSE" },
  { symbol: "XBI", name: "SPDR S&P Biotech ETF", exchange: "NYSE" },
  { symbol: "IBB", name: "iShares Biotechnology ETF", exchange: "NASDAQ" },
  { symbol: "XHB", name: "SPDR S&P Homebuilders ETF", exchange: "NYSE" },
  { symbol: "ITB", name: "iShares U.S. Home Construction ETF", exchange: "NYSE" },
  { symbol: "XOP", name: "SPDR S&P Oil & Gas Exploration & Production ETF", exchange: "NYSE" },
  { symbol: "OIH", name: "VanEck Oil Services ETF", exchange: "NYSE" },
  { symbol: "GDX", name: "VanEck Gold Miners ETF", exchange: "NYSE" },
  { symbol: "GDXJ", name: "VanEck Junior Gold Miners ETF", exchange: "NYSE" },
  { symbol: "SIL", name: "Global X Silver Miners ETF", exchange: "NYSE" },
  { symbol: "KRE", name: "SPDR S&P Regional Banking ETF", exchange: "NYSE" },
  { symbol: "KBE", name: "SPDR S&P Bank ETF", exchange: "NYSE" },
  { symbol: "XRT", name: "SPDR S&P Retail ETF", exchange: "NYSE" },
  { symbol: "IYR", name: "iShares U.S. Real Estate ETF", exchange: "NYSE" },
  { symbol: "JETS", name: "U.S. Global Jets ETF", exchange: "NYSE" },
  { symbol: "PFF", name: "iShares Preferred and Income Securities ETF", exchange: "NASDAQ" },
  { symbol: "SPHD", name: "Invesco S&P 500 High Dividend Low Volatility ETF", exchange: "NYSE" },
  { symbol: "RSP", name: "Invesco S&P 500 Equal Weight ETF", exchange: "NYSE" },
  { symbol: "MDY", name: "SPDR S&P Midcap 400 ETF Trust", exchange: "NYSE" },
  { symbol: "IJH", name: "iShares Core S&P Mid-Cap ETF", exchange: "NYSE" },
  { symbol: "IJR", name: "iShares Core S&P Small-Cap ETF", exchange: "NYSE" },
  { symbol: "VB", name: "Vanguard Small-Cap ETF", exchange: "NYSE" },
  { symbol: "VO", name: "Vanguard Mid-Cap ETF", exchange: "NYSE" },
  { symbol: "VV", name: "Vanguard Large-Cap ETF", exchange: "NYSE" },
  { symbol: "VUG", name: "Vanguard Growth ETF", exchange: "NYSE" },
  { symbol: "VTV", name: "Vanguard Value ETF", exchange: "NYSE" },
  { symbol: "MTUM", name: "iShares MSCI USA Momentum Factor ETF", exchange: "NYSE" },
  { symbol: "QUAL", name: "iShares MSCI USA Quality Factor ETF", exchange: "NYSE" },
  { symbol: "SIZE", name: "iShares MSCI USA Size Factor ETF", exchange: "NYSE" },
  { symbol: "USMV", name: "iShares MSCI USA Min Vol Factor ETF", exchange: "NYSE" },
  { symbol: "SPLV", name: "Invesco S&P 500 Low Volatility ETF", exchange: "NYSE" },
  { symbol: "IWF", name: "iShares Russell 1000 Growth ETF", exchange: "NYSE" },
  { symbol: "IWD", name: "iShares Russell 1000 Value ETF", exchange: "NYSE" },
  { symbol: "IWO", name: "iShares Russell 2000 Growth ETF", exchange: "NYSE" },
  { symbol: "IWN", name: "iShares Russell 2000 Value ETF", exchange: "NYSE" },
];

export function searchStocks(query: string, limit = 10): SearchItem[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  const symbolExact: SearchItem[] = [];
  const symbolStart: SearchItem[] = [];
  const nameMatch: SearchItem[] = [];
  const seen = new Set<string>();

  for (const item of STOCK_DATABASE) {
    if (seen.has(item.symbol)) continue;
    const sym = item.symbol.toLowerCase();
    const name = item.name.toLowerCase();

    if (sym === q) {
      symbolExact.push(item);
      seen.add(item.symbol);
    } else if (sym.startsWith(q)) {
      symbolStart.push(item);
      seen.add(item.symbol);
    } else if (name.includes(q) || sym.includes(q)) {
      nameMatch.push(item);
      seen.add(item.symbol);
    }
  }

  return [...symbolExact, ...symbolStart, ...nameMatch].slice(0, limit);
}
